flake.lock

| Commit                                                                                         | Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`087475f9`](https://github.com/NixOS/nixpkgs/commit/087475f93be76efc4013176fe8d845d7fe921f8a) | `` ocamlPackages.uucd: 15.1.0 → 16.0.0 ``                                    |
| [`21315e31`](https://github.com/NixOS/nixpkgs/commit/21315e31f86f0459ac0731868faeedc3a36ce30e) | `` CODEOWNERS: add myself to LLVM ``                                         |
| [`32cc0423`](https://github.com/NixOS/nixpkgs/commit/32cc04236834f5ba5c14b344f0106bea9 …

chore(flake/nixpkgs): `c04d5652` -> `30439d93`

---

flake.lock

| Commit                                                                                          | Message                                                                        |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| [`630b559c`](https://github.com/catppuccin/nix/commit/630b559cc1cb4c0bdd525af506935323e4ccd5d1) | `` ci: remove backport workflow (#339) ``                                      |
| [`42ec8a76`](https://github.com/catppuccin/nix/commit/42ec8a76f93097ff9a84ca28d53957d03b5cd7dc) | `` chore(modules): update ports (#320) ``                                      |
| [`c0a887d3`](https://github.com/catppuccin/nix/commit/c0a887d347b11515f9c8 …

chore(flake/catppuccin): `45745fe5` -> `630b559c`

---

flake.lock

| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`caaa9b11`](https://github.com/hyprwm/Hyprland/commit/caaa9b11e4763ed0367f81bf97ceaad5175806fc) | `` wlr-output-configuration: Improve output configuration (#7571) ``          |
| [`b1ad2d80`](https://github.com/hyprwm/Hyprland/commit/b1ad2d806634edff656cb5ddc9850ae2c73324e8) | `` dispatchers: fixup dpms toggle (#7875) ``                                  |
| [`22746b30`](https://github.com/hyprwm/Hyprland/commit/22746b304614b313a78 …

chore(flake/hyprland): `9232bc2c` -> `caaa9b11`

---

flake.lock

| Commit                                                                                           | Message                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------- |
| [`77f2a013`](https://github.com/hyprwm/Hyprland/commit/77f2a01304f33a2dc7c9002ca9fb20a7653e6ae1) | `` flake.lock: update nixpkgs `` |
| [`7b56ce65`](https://github.com/hyprwm/Hyprland/commit/7b56ce6521e5ad3b0a2dab6f79a045e79c7aeb82) | `` CI/Nix: add cross build ``    |
| [`32a8caf7`](https://github.com/hyprwm/Hyprland/commit/32a8caf7e7a0609629eb08c91de9f9b23a10c455) | `` Nix: also test cross build `` |

chore(flake/hyprland): `caaa9b11` -> `77f2a013`

---

flake.lock

| Commit                                                                                                      | Message                               |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------- |
| [`853e7bd2`](https://github.com/nix-community/home-manager/commit/853e7bd24f875bac2e3a0cf72f993e917d0f8cf5) | `` direnv: even better nushell fix `` |

chore(flake/home-manager): `57e6b30d` -> `853e7bd2`

---

flake.lock

| [`d3b995c4`](https://github.com/nix-community/NUR/commit/d3b995c4e8d6b52f472c545f387f99ca47f8517a) | `` automatic update `` |

chore(flake/nur): `1cb26887` -> `d3b995c4`

---

flake.lock

| [`10b5e865`](https://github.com/nix-community/NUR/commit/10b5e865f7e2ad5fd8b390e5940f5c3774cfb694) | `` automatic update `` |

chore(flake/nur): `d3b995c4` -> `10b5e865`

---

flake.lock

| Commit                                                                                           | Message                                                                     |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| [`b2143a98`](https://github.com/hyprwm/Hyprland/commit/b2143a98e2719012f8c36211a066f8ebccc950b8) | `` CI/Nix: no longer build with submodules ``                               |
| [`f75f8efb`](https://github.com/hyprwm/Hyprland/commit/f75f8efb1be227e586cc0ba2ce6153ce56e04314) | `` Meson: add tracy dependency ``                                           |
| [`be96787e`](https://github.com/hyprwm/Hyprland/commit/be96787ed086f751455cf713739 …

chore(flake/hyprland): `77f2a013` -> `b2143a98`

---

flake.lock

| Commit                                                                                           | Message                        |
| ------------------------------------------------------------------------------------------------ | ------------------------------ |
| [`e20aef7d`](https://github.com/hyprwm/Hyprland/commit/e20aef7d53fcde1470e8d7672e6a03d814fca97f) | `` opengl: remove debug log `` |

chore(flake/hyprland): `b2143a98` -> `e20aef7d`

---

flake.lock

| [`5e908d3e`](https://github.com/nix-community/nix-vscode-extensions/commit/5e908d3ea3e85d444230077cfa93a378204eca38) | `` action `` |

chore(flake/nix-vscode-extensions): `1a9ad3e4` -> `5e908d3e`

---

flake.lock

| [`cc02909b`](https://github.com/Gerg-L/spicetify-nix/commit/cc02909bbfaa51dfe5849cf6997cd2fd0492e972) | `` CI update 2024-09-27 `` |

chore(flake/spicetify-nix): `2f429398` -> `cc02909b`

---

flake.lock

| Commit                                                                                                      | Message                                            |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`ffe2d07e`](https://github.com/nix-community/home-manager/commit/ffe2d07e771580a005e675108212597e5b367d2d) | `` direnv: hopefully final nushell fix ``          |
| [`0afc2f0f`](https://github.com/nix-community/home-manager/commit/0afc2f0f19470e45a3941926a330f2db55ac2fbf) | `` river: reduce risk of large rebuilds in test `` |

chore(flake/home-manager): `853e7bd2` -> `ffe2d07e`

---

flake.lock

| Commit                                                                                             | Message                                 |
| -------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`118b6b0b`](https://github.com/nix-community/NUR/commit/118b6b0bb575efc1b0632e91e064c4930881bdf6) | `` automatic update ``                  |
| [`bce60b3f`](https://github.com/nix-community/NUR/commit/bce60b3fbdfaf80f255a26cf2597ef76586b2cc3) | `` automatic update ``                  |
| [`a1e60460`](https://github.com/nix-community/NUR/commit/a1e6046036bef187dbe56bbdd25b4a9fca286923) | `` automatic update ``                  |
| [`a3494e9d`](https://github.com/nix-community/NUR/commit/a3494e9def7d07a1 …

chore(flake/nur): `10b5e865` -> `118b6b0b`

---

flake.lock

| [`fcc2206e`](https://github.com/nix-community/NUR/commit/fcc2206eece035720a1dbe8900bf00d069932788) | `` automatic update `` |

chore(flake/nur): `40322094` -> `fcc2206e`

---

flake.lock

| [`93d83fd3`](https://github.com/nix-community/NUR/commit/93d83fd3cb19258aae05f55ce61d6e6b24891fc0) | `` automatic update `` |

chore(flake/nur): `fcc2206e` -> `93d83fd3`

---

flake.lock

| [`eef19587`](https://github.com/nix-community/NUR/commit/eef19587a052e651471cb7be731fb28ef4e62ca3) | `` automatic update `` |
| [`13f5f0af`](https://github.com/nix-community/NUR/commit/13f5f0afe7ebca75d04c314270932ff6b7eddaa6) | `` automatic update `` |

chore(flake/nur): `a632155f` -> `eef19587`

---

flake.lock

| [`566c0500`](https://github.com/nix-community/NUR/commit/566c05008f3968e27fffa55722d1af1718ff059a) | `` automatic update `` |

chore(flake/nur): `eef19587` -> `566c0500`

---

flake.lock

| [`72fcc12f`](https://github.com/nix-community/NUR/commit/72fcc12fb07436d526b3158c7716f1333679b8c8) | `` automatic update `` |

chore(flake/nur): `566c0500` -> `72fcc12f`

---

flake.lock

| [`373fa5cb`](https://github.com/nix-community/NUR/commit/373fa5cb9b1392eaf1058cb0cb2b48391e03a9da) | `` automatic update `` |
| [`7b186f5f`](https://github.com/nix-community/NUR/commit/7b186f5f9000c180cb8b2bbcf1713370e99635a2) | `` automatic update `` |

chore(flake/nur): `72fcc12f` -> `373fa5cb`

---

flake.lock

| [`09b6fea7`](https://github.com/nix-community/NUR/commit/09b6fea7b9d57f3550fdc7222aeda55e50dc5b88) | `` automatic update `` |

chore(flake/nur): `373fa5cb` -> `09b6fea7`

---

flake.lock

| Commit                                                                                                        | Message                                              |
| ------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`eb1bd106`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/eb1bd106cf97ebbb16b6fb2dbb83143564996479) | `` Update cachix/install-nix-action action to v29 `` |

chore(flake/nixpkgs-ruby): `c7a557d4` -> `f13d235d`

---

flake.lock

| Commit                                                                                           | Message                                               |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------- |
| [`2cf6e786`](https://github.com/hyprwm/Hyprland/commit/2cf6e7862a844ad96aa060d63f6774df7e2234a6) | `` dwindle: add config option `split_bias` (#7920) `` |

chore(flake/hyprland): `58669fef` -> `2cf6e786`

---

flake.lock

| [`1765e68c`](https://github.com/nix-community/NUR/commit/1765e68c27bce88618da5a71832f551718e81020) | `` automatic update `` |

chore(flake/nur): `78754dc9` -> `1765e68c`

---

flake.lock

| [`4bcd4211`](https://github.com/nix-community/NUR/commit/4bcd42114ac058ad8be00780dd829debf78308a9) | `` automatic update `` |
| [`b83bef9c`](https://github.com/nix-community/NUR/commit/b83bef9cbca9564e226489cb0d859a5c84822aea) | `` automatic update `` |

chore(flake/nur): `1765e68c` -> `4bcd4211`

---

flake.lock

| [`65a95ae7`](https://github.com/Gerg-L/spicetify-nix/commit/65a95ae7c145ed836ca7d4a1e6be5154125490cf) | `` CI update 2024-09-28 `` |

chore(flake/spicetify-nix): `cc02909b` -> `65a95ae7`

---

flake.lock

| [`1511e273`](https://github.com/nix-community/NUR/commit/1511e2738ed1709e3bddef891dee0903ba5ca62c) | `` automatic update `` |

chore(flake/nur): `4bcd4211` -> `1511e273`

---

flake.lock

| [`70927943`](https://github.com/nix-community/NUR/commit/70927943520aee93363191b0ecc7d163bc05aa2a) | `` automatic update `` |

chore(flake/nur): `1511e273` -> `70927943`

---

flake.lock

| [`69d2128b`](https://github.com/nix-community/NUR/commit/69d2128b623b8d0a2542dcc0cb1fe0df8ff71c2e) | `` automatic update `` |
| [`5c824607`](https://github.com/nix-community/NUR/commit/5c824607149f5c40a04f986d501c37d9c3128759) | `` automatic update `` |

chore(flake/nur): `70927943` -> `69d2128b`

---

flake.lock

| [`08546da0`](https://github.com/nix-community/NUR/commit/08546da084eec64003fb90a2902155ff2a9271af) | `` automatic update `` |

chore(flake/nur): `69d2128b` -> `08546da0`

---

flake.lock

| [`d48ce424`](https://github.com/nix-community/NUR/commit/d48ce4241d67a59751722b28d1b873be02d7903c) | `` automatic update `` |

chore(flake/nur): `08546da0` -> `d48ce424`

---

flake.lock

| [`d148b56d`](https://github.com/nix-community/NUR/commit/d148b56d5f3f8774c8dfabc269bbabd65afde015) | `` automatic update `` |

chore(flake/nur): `d48ce424` -> `d148b56d`

---

flake.lock

| Commit                                                                                           | Message                             |
| ------------------------------------------------------------------------------------------------ | ----------------------------------- |
| [`6f313de9`](https://github.com/hyprwm/Hyprland/commit/6f313de952311282e82461a342c74ea702d9f13a) | `` core: Fix Musl builds (#7934) `` |

chore(flake/hyprland): `2cf6e786` -> `6f313de9`

---

flake.lock

| [`9ce77a59`](https://github.com/nix-community/NUR/commit/9ce77a598fe93eead57f14cece0912ecf89236db) | `` automatic update `` |

chore(flake/nur): `d148b56d` -> `9ce77a59`

---

flake.lock

| Commit                                                                                           | Message                           |
| ------------------------------------------------------------------------------------------------ | --------------------------------- |
| [`d73c1475`](https://github.com/hyprwm/Hyprland/commit/d73c14751ad40fd54d93baac2226f550142b0e74) | `` CI/Nix: git+https -> github `` |

chore(flake/hyprland): `6f313de9` -> `d73c1475`

---

flake.lock

| [`96aee93e`](https://github.com/nix-community/NUR/commit/96aee93e0e6daf3e0f649f2e3e9140c0934678f7) | `` automatic update `` |

chore(flake/nur): `9ce77a59` -> `96aee93e`

---

flake.lock

| [`c24d46ab`](https://github.com/nix-community/NUR/commit/c24d46abffc82fd4c89dec3a2c5eea823175ba08) | `` automatic update `` |
| [`09e1e8d1`](https://github.com/nix-community/NUR/commit/09e1e8d1f0d17a6a7eeb441ae5d91264ee2a2e3e) | `` automatic update `` |
| [`742ea7b8`](https://github.com/nix-community/NUR/commit/742ea7b8a25da31bc42318bcc45fd03e9aed1034) | `` automatic update `` |

chore(flake/nur): `96aee93e` -> `c24d46ab`

---

flake.lock

| Commit                                                                                                            | Message                  |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------ |
| [`41c3f28c`](https://github.com/nix-community/nix-index-database/commit/41c3f28cd02b19a4a728d97ac1827353b90e3e36) | `` flake.lock: Update `` |

chore(flake/nix-index-database): `c7515c2f` -> `41c3f28c`

---

flake.lock

| Commit                                                                                                            | Message                                                 |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| [`a2ab1588`](https://github.com/nix-community/nix-index-database/commit/a2ab1588541ae442bd3a682f8f6bbcbca2672f10) | `` update generated.nix to release 2024-09-29-031659 `` |

chore(flake/nix-index-database): `41c3f28c` -> `a2ab1588`

---

flake.lock

| [`4586a533`](https://github.com/nix-community/NUR/commit/4586a533b8e12ef9be6a672b4d82950ed1e0c2b5) | `` automatic update `` |
| [`d32f9461`](https://github.com/nix-community/NUR/commit/d32f9461879299fe5447874ce0f3068b22635d3d) | `` automatic update `` |

chore(flake/nur): `c24d46ab` -> `4586a533`

---

flake.lock

| [`defec851`](https://github.com/nix-community/NUR/commit/defec851cc882d5f9ee4552b9867aa00175112c6) | `` automatic update `` |

chore(flake/nur): `4586a533` -> `defec851`

---

flake.lock

| [`cf348178`](https://github.com/Gerg-L/spicetify-nix/commit/cf34817877db467a9c881ffa1de3d2822fdc137a) | `` CI update 2024-09-29 `` |

chore(flake/spicetify-nix): `65a95ae7` -> `cf348178`

---

flake.lock

| [`d6c50bc0`](https://github.com/nix-community/NUR/commit/d6c50bc086a44dc5af3ab267b0af64203cba9eaa) | `` automatic update `` |

chore(flake/nur): `defec851` -> `d6c50bc0`

---

flake.lock

| [`2f5cbb7a`](https://github.com/nix-community/nix-vscode-extensions/commit/2f5cbb7a6e05e1d5167e869ba3e7685115da12c6) | `` action `` |

chore(flake/nix-vscode-extensions): `5e908d3e` -> `2f5cbb7a`

---

flake.lock

| [`78703795`](https://github.com/nix-community/NUR/commit/787037957a959c391cede085702224cd5e366af1) | `` automatic update `` |
| [`61bca450`](https://github.com/nix-community/NUR/commit/61bca4508a3fc93822cf2007966a94a0174e1f22) | `` automatic update `` |

chore(flake/nur): `d6c50bc0` -> `78703795`

---

flake.lock

| [`6acf80f8`](https://github.com/nix-community/NUR/commit/6acf80f88c3f8fbf4f95f5df7a936a488a7bca12) | `` automatic update `` |

chore(flake/nur): `78703795` -> `6acf80f8`

---

flake.lock

| [`ebcdd5af`](https://github.com/nix-community/NUR/commit/ebcdd5afc9751dfcb371197e209af22febaf45b9) | `` automatic update `` |

chore(flake/nur): `6acf80f8` -> `ebcdd5af`

---

flake.lock

| [`f3fd2cfb`](https://github.com/nix-community/NUR/commit/f3fd2cfb47f11b53c881db7b2edc86d8c9d55bb5) | `` automatic update `` |

chore(flake/nur): `ebcdd5af` -> `f3fd2cfb`

---

flake.lock

| [`3c37b6df`](https://github.com/nix-community/NUR/commit/3c37b6df4a773825187dd960dc0b330e387d34ce) | `` automatic update `` |

chore(flake/nur): `f3fd2cfb` -> `3c37b6df`

---

flake.lock

| [`4da20986`](https://github.com/nix-community/NUR/commit/4da209862c4aafa83e37b8a69808cde609db4f63) | `` automatic update `` |
| [`e849a364`](https://github.com/nix-community/NUR/commit/e849a364c2890e3e75bda0575c4400b601373580) | `` automatic update `` |
| [`f7cae2fc`](https://github.com/nix-community/NUR/commit/f7cae2fc5cb4c89b3c22095c8a8f73f757949fc8) | `` automatic update `` |
| [`58fea91b`](https://github.com/nix-community/NUR/commit/58fea91b49162a0a7e893e3acedc8f97bbb18aa9) | `` automatic update `` |
| …

chore(flake/nur): `3c37b6df` -> `4da20986`

---

flake.lock

| Commit                                                                                           | Message                                                                      |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------- |
| [`488efab6`](https://github.com/hyprwm/Hyprland/commit/488efab63654a643d76df4997cd932d6fddd8faf) | `` single-pixel-buffer: new protocol impl ``                                 |
| [`6649255d`](https://github.com/hyprwm/Hyprland/commit/6649255d54f45a7e2fedd9b4be85fe5d11229c04) | `` flake.lock: update ``                                                     |
| [`4b00cba3`](https://github.com/hyprwm/Hyprland/commit/4b00cba319dc44294567d06 …

chore(flake/hyprland): `d73c1475` -> `488efab6`

---

flake.lock

| Commit                                                                                                | Message                                  |
| ----------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`ec53a684`](https://github.com/Gerg-L/spicetify-nix/commit/ec53a68450d888d245dbf0d4b0f9365217d0ed5d) | `` CI update 2024-09-30 ``               |
| [`d0a8d745`](https://github.com/Gerg-L/spicetify-nix/commit/d0a8d7455133ec886c4723e5593a314625aaedaf) | `` add TODO.md ``                        |
| [`77a53c2f`](https://github.com/Gerg-L/spicetify-nix/commit/77a53c2fd59f829ace666aa371ec7004c1db5b5f) | `` change to more traditional builder `` |
| …

chore(flake/spicetify-nix): `cf348178` -> `ec53a684`

---

flake.lock

| Commit                                                                                             | Message                                             |
| -------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`58b501ea`](https://github.com/nix-community/NUR/commit/58b501eaed427de88e222820dd6bd225a7d95cd7) | `` automatic update ``                              |
| [`c33dfeca`](https://github.com/nix-community/NUR/commit/c33dfeca43d1d61b478c6efacc59848b7367c5a1) | `` automatic update ``                              |
| [`3ed4a3f3`](https://github.com/nix-community/NUR/commit/3ed4a3f36e538bf16a1034c6e85f66d582b0dc92) | `` automatic update ``                              |
| …

chore(flake/nur): `4da20986` -> `58b501ea`

---

flake.lock

| Commit                                                                                           | Message                                                                              |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------ |
| [`5c6c300a`](https://github.com/hyprwm/Hyprland/commit/5c6c300abfea2539ffad9bcbf857325eec5ab765) | `` wayland/output: send geometry in updateState ``                                   |
| [`6bd33971`](https://github.com/hyprwm/Hyprland/commit/6bd339714160505ab1c4aade659eca6fe426fea5) | `` wlr-output-management: accept 0 refresh rates ``                                  |
| …

chore(flake/hyprland): `f6387536` -> `5c6c300a`

---

flake.lock

| [`f190dd95`](https://github.com/Gerg-L/spicetify-nix/commit/f190dd954b30e6830939fb764cac85c773846435) | `` CI update 2024-10-01 `` |

chore(flake/spicetify-nix): `ec53a684` -> `f190dd95`

---

flake.lock

| [`2e883749`](https://github.com/nix-community/nix-vscode-extensions/commit/2e8837496c0f58c4342ed84d309a8bc57677bc41) | `` action `` |

chore(flake/nix-vscode-extensions): `6b2d41c8` -> `2e883749`

---

flake.lock

| [`718a9b94`](https://github.com/nix-community/nix-vscode-extensions/commit/718a9b948796e17ae2bfff11f023e2b2894e072d) | `` action `` |

chore(flake/nix-vscode-extensions): `2e883749` -> `718a9b94`

---

flake.lock

| [`3e033244`](https://github.com/Gerg-L/spicetify-nix/commit/3e033244348288c6995b155a493a229e499a7c4f) | `` CI update 2024-10-02 `` |

chore(flake/spicetify-nix): `f190dd95` -> `3e033244`

---

flake.lock

| Commit                                                                                           | Message                                                          |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- |
| [`e2426942`](https://github.com/hyprwm/Hyprland/commit/e2426942e5716a742ea353d2a1de7d7760fbbb41) | `` layout: add auto_group to control default grouping (#7883) `` |

chore(flake/hyprland): `5c6c300a` -> `e2426942`

---

flake.lock

| Commit                                                                                         | Message                                                                                 |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`67a452c2`](https://github.com/NixOS/nixpkgs/commit/67a452c21843cf7346d222d2ff74e1eeae3c5463) | `` rhythmbox: use brasero-unwrapped instead of brasero ``                               |
| [`e277415c`](https://github.com/NixOS/nixpkgs/commit/e277415cfed1a4c5bd96183e8ba51c60f046fe22) | `` luaPackages: update on 2024-09-30 ``                                                 |
| …

chore(flake/nixpkgs): `06cf0e1d` -> `27e30d17`

---

flake.lock

| Commit                                                                                          | Message                                               |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| [`bad96d3f`](https://github.com/catppuccin/nix/commit/bad96d3fabf8d2e8f0bf0c2cb899a9fccf01ea03) | `` docs: remove kitty from README's IFD FAQ (#342) `` |

chore(flake/catppuccin): `630b559c` -> `bad96d3f`

---

flake.lock

| Commit                                                                                           | Message                                      |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------- |
| [`aed529f6`](https://github.com/hyprwm/Hyprland/commit/aed529f695bc62f5fa45dc94c545275ebb49bc48) | `` renderer: fix uvBR calculation (#7975) `` |

chore(flake/hyprland): `de68e065` -> `aed529f6`

---

flake.lock

| [`18f1593e`](https://github.com/nix-community/NUR/commit/18f1593e31a3df732df20252a5b18b3e866d77f8) | `` automatic update `` |
| [`370762a6`](https://github.com/nix-community/NUR/commit/370762a6f84c92b147538b2b1843947cd3193c08) | `` automatic update `` |
| [`53f28176`](https://github.com/nix-community/NUR/commit/53f281767c5700f76f7d49c3c34936f989e26512) | `` automatic update `` |
| [`2eda69b6`](https://github.com/nix-community/NUR/commit/2eda69b6d70f2564f95a7b5c41c00b3ac0307ef5) | `` automatic update `` |
| …

chore(flake/nur): `2eaa6a4b` -> `18f1593e`

---

flake.lock

| [`fafbff41`](https://github.com/nix-community/nix-vscode-extensions/commit/fafbff41cdb76134cef79311e5a559571e7f7697) | `` action `` |

chore(flake/nix-vscode-extensions): `6618c358` -> `fafbff41`

---

flake.lock

| Commit                                                                                           | Message                                               |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------- |
| [`1ed925b6`](https://github.com/hyprwm/Hyprland/commit/1ed925b69c2854a3f345cbeb7dca29a6286ca926) | `` internal: fix missing include directive (#7984) `` |

chore(flake/hyprland): `aed529f6` -> `1ed925b6`

---

flake.lock

| [`05603145`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/056031458a00616b5cc7478bee9b9d4fcbb127bf) | `` Update Ruby versions `` |

chore(flake/nixpkgs-ruby): `f13d235d` -> `1e91d8b4`

---

flake.lock

| [`1389b984`](https://github.com/Gerg-L/spicetify-nix/commit/1389b9841aa50f3c5719f77b41041d78a66fb0ed) | `` CI update 2024-10-04 `` |

chore(flake/spicetify-nix): `829a8104` -> `1389b984`

---

flake.lock

| Commit                                                                                                      | Message                                                      |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| [`509dbf8d`](https://github.com/nix-community/home-manager/commit/509dbf8d45606b618e9ec3bbe4e936b7c5bc6c1e) | `` megasync: fix issue with service failing to launch ``     |
| [`30e04f3d`](https://github.com/nix-community/home-manager/commit/30e04f3d477256de3eb6a7cff608e220087537d4) | `` pass-secret-service: add GNUPGHOME to service env vars `` |

chore(flake/home-manager): `437ec620` -> `509dbf8d`

---

flake.lock

| Commit                                                                                           | Message                                                          |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- |
| [`595eb89f`](https://github.com/hyprwm/Hyprland/commit/595eb89f6e16df0e19916e3c02bf5ceac5a61c57) | `` renderer: Fix resize artifacts (stretching, bumps) (#7499) `` |
| [`a815b14b`](https://github.com/hyprwm/Hyprland/commit/a815b14bf1b69b92f82bd09f6845fbdbb2fbe516) | `` monitor: cleanup and modernize scheduleDone ``                |
| [`3a5052a7`](https://github.com/hyprwm/Hyprland/commit/3a5052a714e2a6a2b002dddcac1204960b298f8b) | `` compositor: update all …

chore(flake/hyprland): `1ed925b6` -> `595eb89f`

---

flake.lock

| Commit                                                                                         | Message                                                                            |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| [`d77225b9`](https://github.com/NixOS/nixpkgs/commit/d77225b9f067feff3f2d34feffb9dd1e19f3bac4) | `` home-assistant-custom-lovelace-modules.universal-remote-card: 4.0.5 -> 4.0.6 `` |
| [`65697284`](https://github.com/NixOS/nixpkgs/commit/6569728429ed9a4126e8b3a54d8d82a5a9220478) | `` superfile: 1.1.4 -> 1.1.5 ``                                                    |
| [`48b4aa8e`](https://github.com/NixOS/nixpkgs/commit/48b4aa8ea …

chore(flake/nixpkgs): `27e30d17` -> `bc947f54`

---

flake.lock

| Commit                                                                                           | Message                                                   |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------- |
| [`0ec6072a`](https://github.com/hyprwm/Hyprland/commit/0ec6072a290051a03ab66cfb9bc616b2f5540e64) | `` single-pixel: set buffer size to 1,1 ``                |
| [`3ca699de`](https://github.com/hyprwm/Hyprland/commit/3ca699debffbb97085888835a33f20d0c542128d) | `` opengl: use GL_CLAMP_TO_EDGE instead of GL_CLAMP ``    |
| [`52c09196`](https://github.com/hyprwm/Hyprland/commit/52c09196219313aec2ec1d3d543669bff834d746) | `` monitor: arrange monitors on connect and disconnect …

chore(flake/hyprland): `595eb89f` -> `0ec6072a`

---

flake.lock

| [`e6ad3593`](https://github.com/nix-community/NUR/commit/e6ad3593324e2a96526177ec7c3041ea97bf6946) | `` automatic update `` |
| [`6faaf492`](https://github.com/nix-community/NUR/commit/6faaf492c4d987c06dc6dd4bc8ddad91afc28789) | `` automatic update `` |
| [`1edcc31b`](https://github.com/nix-community/NUR/commit/1edcc31bb5ec6006e1d3021f30de2a04f24a89ca) | `` automatic update `` |
| [`882ce566`](https://github.com/nix-community/NUR/commit/882ce566122ca45ad2f00ad868bfec184923d9db) | `` automatic update `` |
| …

chore(flake/nur): `a62be009` -> `e6ad3593`

---

flake.lock

| Commit                                                                                                        | Message                                         |
| ------------------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`b6142d6f`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/b6142d6f8b7a3ec728ddaee135742bbb5870c1da) | `` README: add section about non-flake usage `` |

chore(flake/nixpkgs-ruby): `afa70833` -> `5b96349e`

---

flake.lock

| [`f532f68a`](https://github.com/Gerg-L/spicetify-nix/commit/f532f68a72549f8ee585aa2f6f7dbe9e2ce5a45c) | `` CI update 2024-10-06 `` |

chore(flake/spicetify-nix): `277107c2` -> `f532f68a`

---

flake.lock

| Commit                                                                                           | Message                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------- |
| [`0c7a7e2d`](https://github.com/hyprwm/Hyprland/commit/0c7a7e2d569eeed9d6025f3eef4ea0690d90845d) | `` version: bump to 0.44.0 `` |

chore(flake/hyprland): `0ec6072a` -> `0c7a7e2d`

---

flake.lock

| [`018196c3`](https://github.com/nix-community/nix-vscode-extensions/commit/018196c371073d669510fd69dd2f6dc0ec608c41) | `` action `` |

chore(flake/nix-vscode-extensions): `43482ab1` -> `018196c3`

---

flake.lock

| Commit                                                                                                      | Message                                                |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`fcf5e608`](https://github.com/nix-community/home-manager/commit/fcf5e608ac65f64463bc0ccc5ea86f2170f20689) | `` kitty: allow float values in settings (#5925) ``    |
| [`bc623830`](https://github.com/nix-community/home-manager/commit/bc623830e619cef86a2d3750625ffe4e24ea7e64) | `` ci: bump cachix/install-nix-action from 27 to 30 `` |

chore(flake/home-manager): `509dbf8d` -> `fcf5e608`

---

flake.lock

| Commit                                                                                                      | Message                                                |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`03863036`](https://github.com/nix-community/home-manager/commit/038630363e7de57c36c417fd2f5d7c14773403e4) | `` xdg-mime type package options (#5920) ``            |
| [`271c83e2`](https://github.com/nix-community/home-manager/commit/271c83e21ea81f39a42ad128384e0e6804956a88) | `` firefox: organize tests by submodule (#5698) ``     |
| [`3ac39b2a`](https://github.com/nix-community/home-manager/commit/3ac39b2a8b7cbfc0f96628d8a84867c885bc988b) | `` zathura: …

chore(flake/home-manager): `fcf5e608` -> `03863036`

---

flake.lock

| Commit                                                                                           | Message                                                                                                      |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------ |
| [`0d70c442`](https://github.com/hyprwm/Hyprland/commit/0d70c442538ba0d1efc63558c859c184367c95ad) | `` screencopy: fix screencopy frames not being cleaned up (#8017) ``                                         |
| [`a364df4c`](https://github.com/hyprwm/Hyprland/commit/a364df4c9e9a73f0460665463028539e3abe4a8b) | `` internal: use clampWindowSize to unify min/maxsize handling …

chore(flake/hyprland): `4e41cda2` -> `0d70c442`

---

flake.lock

| [`5b7e260a`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/5b7e260aa2e7930aed762aef6928a19cb87c0e23) | `` Update Ruby versions `` |

chore(flake/nixpkgs-ruby): `5b96349e` -> `08c66f1d`

---

flake.lock

| Commit                                                                                                | Message                                         |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`194e9bb7`](https://github.com/Gerg-L/spicetify-nix/commit/194e9bb7a43639cbebf26527438ca56defc4c076) | `` Bump actions/checkout from 4.2.0 to 4.2.1 `` |
| [`292e6e18`](https://github.com/Gerg-L/spicetify-nix/commit/292e6e185fe1e710d8f8e23ce3ec9f93e5bb6306) | `` CI update 2024-10-08 ``                      |

chore(flake/spicetify-nix): `4bcc76b9` -> `194e9bb7`

---

flake.lock

| Commit                                                                                           | Message                                                                 |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- |
| [`bc299928`](https://github.com/hyprwm/Hyprland/commit/bc299928ad5571300180eb8edb6742ed3bbf0282) | `` output/xdg-output: avoid sending events to released globals ``       |
| [`ac658500`](https://github.com/hyprwm/Hyprland/commit/ac658500fbebe607f2db83f11c37f0a3a05ef734) | `` keyboard: update group state on change for the sym resolve state ``  |
| [`8cced091`](https://github.com/hyprwm/Hyprland/commit/8cced091f53c92bc8de97b9d3dac20b31980af70) …

chore(flake/hyprland): `e0cfbec6` -> `bc299928`

---

flake.lock

| [`a1cbed68`](https://github.com/nix-community/NUR/commit/a1cbed680b97a7c0310aed1959cc9f9934d6e795) | `` automatic update `` |
| [`92d1b587`](https://github.com/nix-community/NUR/commit/92d1b58703d08b78dd50f238f673bdb333c7b374) | `` automatic update `` |
| [`14d046e4`](https://github.com/nix-community/NUR/commit/14d046e499df678618b37aa6a0e1f26e243de5cc) | `` automatic update `` |
| [`39fc87f6`](https://github.com/nix-community/NUR/commit/39fc87f67f57c77f889da98675bba35e95193213) | `` automatic update `` |
| …

chore(flake/nur): `3fce8e9b` -> `a1cbed68`

---

flake.lock

| [`202de6e5`](https://github.com/nix-community/NUR/commit/202de6e51b808ed907886a74f7ea6b4ce0b47555) | `` automatic update `` |
| [`cff8205c`](https://github.com/nix-community/NUR/commit/cff8205c862dddbb16765e956d7807861743bfcb) | `` automatic update `` |
| [`4a10103d`](https://github.com/nix-community/NUR/commit/4a10103d00ead394e7edc85266056f4b4e320b1b) | `` automatic update `` |
| [`9b4b4598`](https://github.com/nix-community/NUR/commit/9b4b459852d217303a58e7c180c7fa48aa462183) | `` automatic update `` |
| …

chore(flake/nur): `a1cbed68` -> `202de6e5`

---

flake.lock

| Commit                                                                                                      | Message                                                  |
| ----------------------------------------------------------------------------------------------------------- | -------------------------------------------------------- |
| [`342a1d68`](https://github.com/nix-community/home-manager/commit/342a1d682386d3a1d74f9555cb327f2f311dda6e) | `` flake.lock: Update ``                                 |
| [`03f8e0b3`](https://github.com/nix-community/home-manager/commit/03f8e0b3b3ca4f49d11bf0264dbff465d6ae9aae) | `` snixembed: add module ``                              |
| [`8bb5d53c`](https://github.com/nix-community/home-manager/commit/8bb5d53c5847d9a9b2ad1bda49f9aa9df0de282a) | `` …

chore(flake/home-manager): `03863036` -> `342a1d68`

---

flake.lock

| [`b4702ed0`](https://github.com/Gerg-L/spicetify-nix/commit/b4702ed0b3d634367e28c4d042bd1fd3fb29b692) | `` CI update 2024-10-11 `` |

chore(flake/spicetify-nix): `d6e8bdf8` -> `b4702ed0`

---

flake.lock

| Commit                                                                                           | Message                                                                   |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------- |
| [`7564b26b`](https://github.com/hyprwm/Hyprland/commit/7564b26b7d386d248eaa47c1a481c09eefd8e3ca) | `` internal: improve version query and define HYPRLAND_VERSION (#8034) `` |
| [`178a300e`](https://github.com/hyprwm/Hyprland/commit/178a300eeaf006fed4c8c9a599657b4530f65559) | `` xwayland: minor cleanups and fixes (#8076) ``                          |
| [`d655a103`](https://github.com/hyprwm/Hyprland/commit/d655a10381f01212635f2eadd69e1f22930 …

chore(flake/hyprland): `b65773be` -> `7564b26b`

---

flake.lock

| Commit                                                                                                      | Message                |
| ----------------------------------------------------------------------------------------------------------- | ---------------------- |
| [`58283095`](https://github.com/nix-community/home-manager/commit/582830954264080aae93f751c3cdc58df600d2d1) | `` vifm: add module `` |

chore(flake/home-manager): `342a1d68` -> `58283095`

---

flake.lock

| [`1d874e69`](https://github.com/nix-community/NUR/commit/1d874e69d2352f5bdb55843ff3ceaa5978a24da5) | `` automatic update `` |
| [`abf82f0f`](https://github.com/nix-community/NUR/commit/abf82f0f0338c25322e0653c2b7e09814da7b2f7) | `` automatic update `` |
| [`249b147c`](https://github.com/nix-community/NUR/commit/249b147c8b96ea9bfc873723f82f88f61f685bb0) | `` automatic update `` |
| [`fc80a73f`](https://github.com/nix-community/NUR/commit/fc80a73f0318005f8f9c9193a6c62ea0469276d1) | `` automatic update `` |
| …

chore(flake/nur): `0eb5a0ee` -> `1d874e69`

---

flake.lock

| Commit                                                                                           | Message                                                                          |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------- |
| [`ee8116ac`](https://github.com/hyprwm/Hyprland/commit/ee8116ac5dc412dce924a0163074ce7988dd0cfc) | `` input: Fix VRR for constrained cursors (#6877) ``                             |
| [`f5db4839`](https://github.com/hyprwm/Hyprland/commit/f5db4839730643169b7e8b7fb6ae2fbb8743ebe9) | `` drm-timeline: Add check for conflicting acquire and release points (#8083) `` |

chore(flake/hyprland): `7564b26b` -> `ee8116ac`

---

flake.lock

| [`79466d1c`](https://github.com/nix-community/NUR/commit/79466d1c9bac4f779dd10a06deb7cae51be4540e) | `` automatic update `` |
| [`b280bce5`](https://github.com/nix-community/NUR/commit/b280bce5874e7c344fbf65ef2d4992cd96ad2557) | `` automatic update `` |
| [`b1d7aba2`](https://github.com/nix-community/NUR/commit/b1d7aba2c87bbeabc2ca0ca25f3949c6a66a3d1e) | `` automatic update `` |
| [`82328bf3`](https://github.com/nix-community/NUR/commit/82328bf3fa31c8663729aab8309eebe37e687d2e) | `` automatic update `` |
| …

chore(flake/nur): `75a800a7` -> `79466d1c`

---

flake.lock

| Commit                                                                                           | Message                                                      |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------ |
| [`1822707c`](https://github.com/hyprwm/Hyprland/commit/1822707c7e7394ce8c7572f2fe890763a307f499) | `` drm-syncobj: fix crash on missing timelines ``            |
| [`c3f7c9bb`](https://github.com/hyprwm/Hyprland/commit/c3f7c9bbb52b9ad3d24ccfcc5c552ed16c9985a5) | `` xcursor: don't crash on broken permissions in X themes `` |

chore(flake/hyprland): `ee8116ac` -> `1822707c`

---

flake.lock

| [`c6b7ef33`](https://github.com/nix-community/NUR/commit/c6b7ef33feea3c22ef420ebdf97f547a34d16adf) | `` automatic update `` |
| [`af31ea38`](https://github.com/nix-community/NUR/commit/af31ea380af72ca02bfa657e7ffcde5538c71e73) | `` automatic update `` |
| [`2783ec9a`](https://github.com/nix-community/NUR/commit/2783ec9ab9ea630d8f7657bee76cef81e0c125e6) | `` automatic update `` |
| [`dfb94a40`](https://github.com/nix-community/NUR/commit/dfb94a4063e762fb282b91af80bff1ad1ddeb27f) | `` automatic update `` |
| …

chore(flake/nur): `79466d1c` -> `c6b7ef33`

---

flake.lock

| [`59aa5259`](https://github.com/Gerg-L/spicetify-nix/commit/59aa525938e501bdacad3753034e864a426b66f5) | `` CI update 2024-10-12 `` |

chore(flake/spicetify-nix): `b4702ed0` -> `59aa5259`

---

flake.lock

| Commit                                                                                           | Message                                                                           |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------- |
| [`e7fd0f5a`](https://github.com/hyprwm/Hyprland/commit/e7fd0f5aec85c11a8eaf5e1abf8504f0a6d0710e) | `` layout: deny auto-grouping a new floating window into a tiled group (#8108) `` |
| [`abfd550e`](https://github.com/hyprwm/Hyprland/commit/abfd550ee228ea23058039790e792b45d2467c8d) | `` xwm: avoid infinite parent lookup loop in lookupParentExists ``                |
| …

chore(flake/hyprland): `1822707c` -> `e7fd0f5a`

---

flake.lock

| Commit                                                                                                               | Message                                 |
| -------------------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [`1238ef47`](https://github.com/nix-community/nix-vscode-extensions/commit/1238ef474677e7e925c796323c53d1b92aea9806) | `` action ``                            |
| [`a3a0f7ea`](https://github.com/nix-community/nix-vscode-extensions/commit/a3a0f7ea4c2bfa7674607e4f08b3c0bc0c128914) | `` fix: update codelldb download url `` |

chore(flake/nix-vscode-extensions): `018196c3` -> `1238ef47`

---

flake.lock

| Commit                                                                                           | Message                                                                             |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------- |
| [`01c2ff34`](https://github.com/hyprwm/Hyprland/commit/01c2ff34ddcb5995409c33c2b549e93b98b56d6b) | `` layout: simplify the conditions to autogroup (#8120) ``                          |
| [`22b1370a`](https://github.com/hyprwm/Hyprland/commit/22b1370ae512c92d84bbcd4cff2a3f8a4496c994) | `` IME: Fixup IME popup candidate windows position when scale is not 1.0 (#8117) `` |
| …

chore(flake/hyprland): `e7fd0f5a` -> `01c2ff34`

---

flake.lock

| [`a83d478b`](https://github.com/Gerg-L/spicetify-nix/commit/a83d478b4512fdb80e2dd5a86c5d67e73e0c8b7e) | `` CI update 2024-10-16 `` |

chore(flake/spicetify-nix): `3dfd050f` -> `a83d478b`

---

flake.lock

| Commit                                                                                           | Message                                                            |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------ |
| [`b57086aa`](https://github.com/hyprwm/Hyprland/commit/b57086aa4362117c1f1025246f618d760e44b026) | `` window: properly break cycles in X11TransientFor ``             |
| [`09581d32`](https://github.com/hyprwm/Hyprland/commit/09581d32fd465c5c4ff868090369ee67516c38a9) | `` hyprpm: Fix crashes due to misplaced fmt argument(s) (#8140) `` |
| [`86e9f69a`](https://github.com/hyprwm/Hyprland/commit/86e9f69a69990feb880dadd0c2b8c067b2a96fa9) | `` layout: move …

chore(flake/hyprland): `01c2ff34` -> `b57086aa`

---

flake.lock

| [`a2a26f1b`](https://github.com/nix-community/nix-vscode-extensions/commit/a2a26f1bada2202572599346eb952bd3e130af66) | `` action `` |
| [`4dfd7581`](https://github.com/nix-community/nix-vscode-extensions/commit/4dfd7581aaf0f25d3b7695a10dcfb1dfe4ebb953) | `` action `` |
| [`66dc136c`](https://github.com/nix-community/nix-vscode-extensions/commit/66dc136c3c73a2220e604cadc11bb5e382084a67) | `` action `` |

chore(flake/nix-vscode-extensions): `81a5fdad` -> `a2a26f1b`

---

flake.lock

| Commit                                                                                                      | Message                                                   |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`122f7054`](https://github.com/nix-community/home-manager/commit/122f70545b29ccb922e655b08acfe05bfb44ec68) | `` firefox: change container.json version to 5 ``         |
| [`802b3cb2`](https://github.com/nix-community/home-manager/commit/802b3cb2d45ad66619ea8ad19b280baa460556d2) | `` espanso: use `launcher` command on Linux ``            |
| [`09a0c0c0`](https://github.com/nix-community/home-manager/commit/09a0c0c02953318bf94425738c7061ffdc4cba75) | …

chore(flake/home-manager): `2a4fd1cf` -> `122f7054`

---

flake.lock

| Commit                                                                                         | Message                                                                                  |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- |
| [`4c2fcb09`](https://github.com/NixOS/nixpkgs/commit/4c2fcb090b1f3e5b47eaa7bd33913b574a11e0a0) | `` ocamlPackages.uuidm: 0.9.8 → 0.9.9 ``                                                 |
| [`4d56f18a`](https://github.com/NixOS/nixpkgs/commit/4d56f18a82430e1bc51cb7f8dfa2ed61bdf0447a) | `` maintainers/team-list: remove asymmetric from jitsi ``                                |
| …

chore(flake/nixpkgs): `a3c0b3b2` -> `4c2fcb09`

---

flake.lock

| [`e20f3e31`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/e20f3e31687c0b2cf09421b0dd3a5504f064da89) | `` Update Ruby versions `` |

chore(flake/nixpkgs-ruby): `2337dcf3` -> `38d584e0`

---

flake.lock

| Commit                                                                                           | Message                                                                  |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------ |
| [`08cc063e`](https://github.com/hyprwm/Hyprland/commit/08cc063e175e48cea44d26b7e3762f4b8611f0c5) | `` monitor: avoid crash on released buffer in surf ``                    |
| [`a17850e4`](https://github.com/hyprwm/Hyprland/commit/a17850e41cabb455880b43032cf65041cd77ef25) | `` layersurface: fixup brace style ``                                    |
| [`6a5c3420`](https://github.com/hyprwm/Hyprland/commit/6a5c342063814ca7e3d181f324c71305bcd656a …

chore(flake/hyprland): `b57086aa` -> `08cc063e`

---

flake.lock

| Commit                                                                                           | Message                                                                     |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| [`5e96d738`](https://github.com/hyprwm/Hyprland/commit/5e96d738e698f22969ca502d042d5751711c6d8a) | `` hyprpm: Add option to notify on fail and keep original notify (#8167) `` |
| [`9df0f0b6`](https://github.com/hyprwm/Hyprland/commit/9df0f0b66c66706c9ce8cf9f80e834d5abfc1e96) | `` renderer: fix floating window damage (#8182) ``                          |
| [`4093b993`](https://github.com/hyprwm/Hyprland/commit/4093b993a2c79ce576702641134 …

chore(flake/hyprland): `08cc063e` -> `5e96d738`

---

flake.lock

| Commit                                                                                           | Message                                              |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------- |
| [`cdac6497`](https://github.com/hyprwm/Hyprland/commit/cdac64970e894c3211d94da8925fbf905b52a594) | `` Makefile: fix legacyrendererdebug typo (#8214) `` |

chore(flake/hyprland): `6e0aadc5` -> `cdac6497`

---

flake.lock

| [`087ec372`](https://github.com/nix-community/nix-vscode-extensions/commit/087ec37265ff1c8641086ee2a51450963494cdeb) | `` action `` |

chore(flake/nix-vscode-extensions): `4809c92c` -> `087ec372`

---

flake.lock

| [`60fcca8c`](https://github.com/nix-community/NUR/commit/60fcca8c5b60a1889b78827890d42100387cdcf5) | `` automatic update `` |
| [`232725a2`](https://github.com/nix-community/NUR/commit/232725a2d7227ac09e17d3eddcfbd4c51176fb90) | `` automatic update `` |
| [`7b379d1a`](https://github.com/nix-community/NUR/commit/7b379d1ac27df4ec74e0c380397ad382d8be96a8) | `` automatic update `` |
| [`403e35b3`](https://github.com/nix-community/NUR/commit/403e35b3fb60d75e36919ca99d8020f3e75ffe5b) | `` automatic update `` |
| …

chore(flake/nur): `762d1ae1` -> `60fcca8c`

---

flake.lock

| [`933469d5`](https://github.com/Gerg-L/spicetify-nix/commit/933469d5d0bc50bcc3918aa0f425d68fdd7c0736) | `` CI update 2024-10-24 `` |

chore(flake/spicetify-nix): `b9d88696` -> `933469d5`

---

flake.lock

| Commit                                                                                           | Message                                                    |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------- |
| [`f603a22a`](https://github.com/hyprwm/Hyprland/commit/f603a22af0c8890b9742d761d44f0b595740f5b1) | `` internal: Remove some unused lambda captures (#8218) `` |

chore(flake/hyprland): `cdac6497` -> `f603a22a`

---

flake.lock

| [`fd9ae552`](https://github.com/Gerg-L/spicetify-nix/commit/fd9ae55223412b9dc5fedd3e9c3d1d18804577af) | `` CI update 2024-10-25 `` |

chore(flake/spicetify-nix): `933469d5` -> `fd9ae552`

---

flake.lock

| Commit                                                                                                      | Message                                                   |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`c77c3bb2`](https://github.com/nix-community/home-manager/commit/c77c3bb23390a9ba91860e721edde54856fc5f7a) | `` yazi: enable shell integration values by default ``    |
| [`8bd6e0a1`](https://github.com/nix-community/home-manager/commit/8bd6e0a1a805c373686e21678bb07f23293d357b) | `` nixgl: add support for channel-based configuration ``  |
| [`7a587970`](https://github.com/nix-community/home-manager/commit/7a5879707bb49c350aee7ab270c917584d430193) | …

chore(flake/home-manager): `a4353cc4` -> `c77c3bb2`

---

flake.lock

| [`7d7cbe07`](https://github.com/nix-community/NUR/commit/7d7cbe07852abdfd4a3bc09cb565e294f3251548) | `` automatic update `` |
| [`2e1068ad`](https://github.com/nix-community/NUR/commit/2e1068ad9868845629bdca56df78546182ec3df6) | `` automatic update `` |
| [`5a807a98`](https://github.com/nix-community/NUR/commit/5a807a981707c8bdea38a643b499a9ac4d493132) | `` automatic update `` |
| [`fe1086c1`](https://github.com/nix-community/NUR/commit/fe1086c18a437ff5f5fbb95dc66abbf61e764cbe) | `` automatic update `` |
| …

chore(flake/nur): `20a5ac55` -> `7d7cbe07`

---

flake.lock

| Commit                                                                                           | Message                                             |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------- |
| [`f0e023bf`](https://github.com/hyprwm/Hyprland/commit/f0e023bff2f2a25ffe5ed3166f55f7274d17c6bc) | `` security-context: avoid UB in C macro (#8229) `` |

chore(flake/hyprland): `3cec45d8` -> `f0e023bf`

---

flake.lock

| [`0d53b783`](https://github.com/nix-community/nix-vscode-extensions/commit/0d53b7836079cda476fab76bf9becfdd475a5d1d) | `` action `` |

chore(flake/nix-vscode-extensions): `087ec372` -> `0d53b783`

---

flake.lock

| Commit                                                                                                      | Message                                           |
| ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`93435d27`](https://github.com/nix-community/home-manager/commit/93435d27d250fa986bfec6b2ff263161ff8288cb) | `` direnv: add support for mise integration ``    |
| [`0c0268a3`](https://github.com/nix-community/home-manager/commit/0c0268a3c80d30b989d0aadbd65f38d4fa27a9a0) | `` eza: add color option ``                       |
| [`c0e23159`](https://github.com/nix-community/home-manager/commit/c0e23159872e2e2135c7eb5cf96cd36cfe6ee1f4) | `` git-credential-oauth: add …

chore(flake/home-manager): `c77c3bb2` -> `93435d27`

---

flake.lock

| Commit                                                                                                | Message                                         |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [`ebbc0161`](https://github.com/Gerg-L/spicetify-nix/commit/ebbc0161954fbba0c3b5873f9b63f51f58f59a83) | `` Bump actions/checkout from 4.2.1 to 4.2.2 `` |

chore(flake/spicetify-nix): `fd9ae552` -> `ebbc0161`

---

flake.lock

| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`e5384774`](https://github.com/hyprwm/Hyprland/commit/e5384774a8258e44cc7f7b690ce4f6ad1f92b562) | `` example/hyprland-session.service: add support for xdg autostart (#8230) `` |

chore(flake/hyprland): `f0e023bf` -> `e5384774`

---

flake.lock

| Commit                                                                                           | Message                                                                                       |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------- |
| [`0b29caf9`](https://github.com/hyprwm/Hyprland/commit/0b29caf9ab86518ff474eed5e7d19c12f96ebbd0) | `` core: fix group members disappearing when you move the group to another monitor (#8237) `` |
| [`3dd8db83`](https://github.com/hyprwm/Hyprland/commit/3dd8db83f166733d1dd6a753bd6eb07727320768) | `` pointer: add default auto for no_hw_cursors ``                                             |
| …

chore(flake/hyprland): `e5384774` -> `0b29caf9`

---

flake.lock

| Commit                                                                                                      | Message                                                   |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- |
| [`e8341405`](https://github.com/nix-community/home-manager/commit/e83414058edd339148dc142a8437edb9450574c8) | `` flake.lock: Update ``                                  |
| [`05d9bee4`](https://github.com/nix-community/home-manager/commit/05d9bee4a5155758aec3c3807c0e342b9f253522) | `` git-credential-oauth: fix use of mkIf and add tests `` |

chore(flake/home-manager): `93435d27` -> `e8341405`

---

flake.lock

| Commit                                                                                          | Message                                                                                 |
| ----------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`f99984a7`](https://github.com/catppuccin/nix/commit/f99984a7f4e2a7f92893443dc1d1971d0ff1fe23) | `` docs: fix invalid link (#350) ``                                                     |
| [`a38592df`](https://github.com/catppuccin/nix/commit/a38592df7b062bd589498db3afb958587ad9096c) | `` style: format 641cfc3 ``                                                             |
| …

chore(flake/catppuccin): `96cf8b4a` -> `f99984a7`

---

flake.lock

| Commit                                                                                          | Message                                                         |
| ----------------------------------------------------------------------------------------------- | --------------------------------------------------------------- |
| [`0b7bf046`](https://github.com/catppuccin/nix/commit/0b7bf04628414a402d255924f65e9a0d1a53d92b) | `` feat(home-manager/fcitx5): add accent support (#343) ``      |
| [`250c9865`](https://github.com/catppuccin/nix/commit/250c9865beae02ffaee4f49f7ab39137fc235cda) | `` feat(home-manager): update yazi for accent support (#360) `` |

chore(flake/catppuccin): `f99984a7` -> `0b7bf046`

---

flake.lock

| Commit                                                                                           | Message                                                                  |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------ |
| [`6cf193e1`](https://github.com/hyprwm/Hyprland/commit/6cf193e1662f6f750e964a3e174ae017246b4d48) | `` layout: don't snap to self and allow same-pid snaps ``                |
| [`b1120ec4`](https://github.com/hyprwm/Hyprland/commit/b1120ec4334abdb57677354dfcdcf48b6c34f397) | `` layout: window snapping cleanup + fixes ``                            |
| [`5d4b54b0`](https://github.com/hyprwm/Hyprland/commit/5d4b54b01286c10d4b6bf402a772b5938b054ce …

chore(flake/hyprland): `a3d3b4fd` -> `6cf193e1`

---

flake.lock

| [`6dd52674`](https://github.com/Gerg-L/spicetify-nix/commit/6dd526742ecfbf5a589ed1327710cbe03ac592a1) | `` CI update 2024-10-28 `` |

chore(flake/spicetify-nix): `9418361f` -> `6dd52674`

---

flake.lock

| [`32b83261`](https://github.com/nix-community/nix-vscode-extensions/commit/32b832611420b11892ae164ace68cad8bae3a0ab) | `` action `` |

chore(flake/nix-vscode-extensions): `88bf7381` -> `32b83261`

---

flake.lock

| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`d679d200`](https://github.com/hyprwm/Hyprland/commit/d679d200299ed4670f0d0f138c793d5f507b7cec) | `` seat: avoid sending pointless 'keymap' and 'repeat_info' events (#8276) `` |
| [`7188ee4f`](https://github.com/hyprwm/Hyprland/commit/7188ee4f992966c5793efebd6dc70ab377820066) | `` hyprctl: move setprop into dispatchers (#8275) ``                          |
| [`c7315617`](https://github.com/hyprwm/Hyprland/commit/c7315617eb6186912d0 …

chore(flake/hyprland): `6cf193e1` -> `d679d200`

---

flake.lock

| [`be01145d`](https://github.com/nix-community/nix-vscode-extensions/commit/be01145d66a5cdaf0a620b8b277a8e05f1fba84b) | `` action `` |

chore(flake/nix-vscode-extensions): `32b83261` -> `be01145d`

---

flake.lock

| [`446351c3`](https://github.com/Gerg-L/spicetify-nix/commit/446351c37e053a0098aa19d8c61448bbcfd8f0cc) | `` CI update 2024-10-29 `` |

chore(flake/spicetify-nix): `6dd52674` -> `446351c3`

---

flake.lock

| Commit                                                                                             | Message                                  |
| -------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| [`142092eb`](https://github.com/nix-community/NUR/commit/142092eb842a145ed21ea07425d52e73d72fe856) | `` automatic update ``                   |
| [`39324635`](https://github.com/nix-community/NUR/commit/393246354e12f6f09068c87dad6e8bc20be42ecd) | `` automatic update ``                   |
| [`54ad9b9d`](https://github.com/nix-community/NUR/commit/54ad9b9d402140f7dadb9d9de6d9c21ebbcc9072) | `` automatic update ``                   |
| [`0730f292`](https://github.com/nix-community/NUR/commit/0730f292b69 …

chore(flake/nur): `917fe0f3` -> `142092eb`

---

flake.lock

| Commit                                                                                           | Message                                                                     |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
| [`7c7a84ff`](https://github.com/hyprwm/Hyprland/commit/7c7a84ff60f8c1e00c6a0de3f7656f0bbd933d56) | `` internal: more profiling less calls and local copies (#8300) ``          |
| [`a0b2169e`](https://github.com/hyprwm/Hyprland/commit/a0b2169ed600b71627188dcd208b26911da8d583) | `` input: revert #8279 ``                                                   |
| [`ee91df62`](https://github.com/hyprwm/Hyprland/commit/ee91df62f0be6ac65eae0eb3ed7 …

chore(flake/hyprland): `d679d200` -> `7c7a84ff`

---

flake.lock

| [`238dc7ef`](https://github.com/nix-community/nix-vscode-extensions/commit/238dc7efbe88c5ae226f849b73cd809f3ffbd001) | `` action `` |

chore(flake/nix-vscode-extensions): `be01145d` -> `238dc7ef`

---

flake.lock

| [`bdda106f`](https://github.com/nix-community/nix-vscode-extensions/commit/bdda106fe8c2beda62338254783c562bfb5648a2) | `` action `` |

chore(flake/nix-vscode-extensions): `238dc7ef` -> `bdda106f`

---

flake.lock

| Commit                                                                                           | Message                                                                |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------- |
| [`93b4478e`](https://github.com/hyprwm/Hyprland/commit/93b4478e70af6ffb08a4a66a6d0364c3296db296) | `` snap: add option `border_overlap` and other improvements (#8289) `` |

chore(flake/hyprland): `7c7a84ff` -> `93b4478e`

---

flake.lock

| Commit                                                                                                      | Message                                                     |
| ----------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| [`1743615b`](https://github.com/nix-community/home-manager/commit/1743615b61c7285976f85b303a36cdf88a556503) | `` podman: add module ``                                    |
| [`8ca921e5`](https://github.com/nix-community/home-manager/commit/8ca921e5a806b5b6171add542defe7bdac79d189) | `` git-credential-oauth: fix ordering of git extraConfig `` |

chore(flake/home-manager): `e8341405` -> `1743615b`

---

flake.lock

| [`96dcbddd`](https://github.com/nix-community/nix-vscode-extensions/commit/96dcbddd24edc60ad47f41bb2a73e06099eba4af) | `` action `` |

chore(flake/nix-vscode-extensions): `bdda106f` -> `96dcbddd`

---

flake.lock

| Commit                                                                                           | Message                                                      |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------ |
| [`32b18179`](https://github.com/hyprwm/Hyprland/commit/32b18179dd789cde948c97eb3c2ebbdd6af36bf7) | `` CMake: systemd fixes ``                                   |
| [`29e7dc64`](https://github.com/hyprwm/Hyprland/commit/29e7dc642831801d14480cf7e4bb19f6ffb118e9) | `` Systemd fixes ``                                          |
| [`3c0605c6`](https://github.com/hyprwm/Hyprland/commit/3c0605c68e50416819fea471a8fbef05e4a18684) | `` hyprland-systemd.desktop improvements …

chore(flake/hyprland): `93b4478e` -> `32b18179`

---

flake.lock

| Commit                                                                                          | Message                                   |
| ----------------------------------------------------------------------------------------------- | ----------------------------------------- |
| [`191fbf2d`](https://github.com/catppuccin/nix/commit/191fbf2d81a63fad8f62f1233c0051f09b75d0ad) | `` chore(modules): update ports (#345) `` |

chore(flake/catppuccin): `0b7bf046` -> `191fbf2d`

---

flake.lock

| [`187f8309`](https://github.com/nix-community/NUR/commit/187f8309facb4c1e05dc068dea2e10c38e8f6b4b) | `` automatic update `` |
| [`b880c8c3`](https://github.com/nix-community/NUR/commit/b880c8c347dd996bd7d4e9e139e15ee210e236cd) | `` automatic update `` |
| [`3d720530`](https://github.com/nix-community/NUR/commit/3d720530c32273537ef723a8b5f72c0ecdd1ad2e) | `` automatic update `` |
| [`a7b165eb`](https://github.com/nix-community/NUR/commit/a7b165eb4058b48dc60ca727a2c0cbba4236b8dd) | `` automatic update `` |
| …

chore(flake/nur): `761c6a7d` -> `187f8309`

---

flake.lock

| [`defcdbfd`](https://github.com/Gerg-L/spicetify-nix/commit/defcdbfdf0890df65685e25e8920d68035cb7720) | `` CI update 2024-11-01 `` |
| [`22d250d6`](https://github.com/Gerg-L/spicetify-nix/commit/22d250d6a4dcc492a2d8836d3f2c901a09e7cb76) | `` CI update 2024-10-31 `` |

chore(flake/spicetify-nix): `1c482c8b` -> `defcdbfd`

---

flake.lock

| Commit                                                                                           | Message                                                    |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------- |
| [`40081cb3`](https://github.com/hyprwm/Hyprland/commit/40081cb330fa838ad9c0a7b87c20b2300ea7fb38) | `` renderer: improve api around new framebuffer changes `` |

chore(flake/hyprland): `32b18179` -> `40081cb3`

---

flake.lock

| [`ae767b09`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/ae767b0995eec7bc7985c43e7dc177b059c31506) | `` Update Ruby versions `` |

chore(flake/nixpkgs-ruby): `38d584e0` -> `87caf2b8`

---

flake.lock

| Commit                                                                                         | Message                                                                             |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`7ffd9ae6`](https://github.com/NixOS/nixpkgs/commit/7ffd9ae656aec493492b44d0ddfb28e79a1ea25d) | `` Revert "bundler: 2.5.16 -> 2.5.21" (#353045) ``                                  |
| [`3e6843e8`](https://github.com/NixOS/nixpkgs/commit/3e6843e8d5a20fbf76e8c939c7c6f29977d87f8b) | `` terraform-providers.google-beta: 6.7.0 -> 6.9.0 ``                               |
| …

chore(flake/nixpkgs): `807e9154` -> `7ffd9ae6`

---

flake.lock

| Commit                                                                                           | Message                                                                  |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------ |
| [`cd0d0491`](https://github.com/hyprwm/Hyprland/commit/cd0d0491261728260de3d1aff150e1b6c05f9e86) | `` flake.lock: update xdph ``                                            |
| [`180c26ad`](https://github.com/hyprwm/Hyprland/commit/180c26ada6233c3c59c331cb14a64aac1eeb2941) | `` renderer: safeguard against non-sampleable currentFB in blurMainFb `` |
| [`5833abbb`](https://github.com/hyprwm/Hyprland/commit/5833abbbd11dca718379863cb2fb5c2423f5d7e …

chore(flake/hyprland): `40081cb3` -> `cd0d0491`

---

flake.lock

| [`2d871e2a`](https://github.com/Gerg-L/spicetify-nix/commit/2d871e2a5fb8c9d8d04a3bdd8f206aec81df2d6d) | `` CI update 2024-11-04 `` |

chore(flake/spicetify-nix): `c29215e2` -> `2d871e2a`

---

flake.lock

| [`16ca007e`](https://github.com/nix-community/nix-vscode-extensions/commit/16ca007ec37c29a8b97e4899f33c013defbdb2f9) | `` action `` |

chore(flake/nix-vscode-extensions): `4a91ab65` -> `16ca007e`

---

flake.lock

| Commit                                                                                           | Message                                        |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------- |
| [`88e9e039`](https://github.com/hyprwm/Hyprland/commit/88e9e0394541a853600bc2c910005c05fa156269) | `` renderer: add expand_undersized_textures `` |
| [`0fb9a045`](https://github.com/hyprwm/Hyprland/commit/0fb9a04526b06adfb3fd16b64e13b7d110ae7855) | `` flake.lock: update xdph ``                  |
| [`44899cd5`](https://github.com/hyprwm/Hyprland/commit/44899cd5488831b147f385f201959625bd010898) | `` nix/overlays: fix xdph overlay ``           |

chore(flake/hyprland): `cd0d0491` -> `88e9e039`

---

flake.lock

| Commit                                                                                           | Message                                                                                           |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------- |
| [`db249648`](https://github.com/hyprwm/Hyprland/commit/db249648776875ce3142141d0d3055e43ce606aa) | `` xwayland: Support cross DnD from Wayland (#8708) ``                                            |
| [`9f7a96b9`](https://github.com/hyprwm/Hyprland/commit/9f7a96b997d90c4c188f3837e02859a25a05611e) | `` core/data: Use pointer focus for DnD operations (#8707) `` …

chore(flake/hyprland): `5329298b` -> `db249648`

---

flake.lock

| Commit                                                                                         | Message                                                                                         |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| [`362f987f`](https://github.com/NixOS/nixpkgs/commit/362f987f977ae628b5299f88f6d76a170ba18df6) | `` codesnap: init at 0.8.2 ``                                                                   |
| [`518ae8fd`](https://github.com/NixOS/nixpkgs/commit/518ae8fd583e3e2ba9bc7c5b3643b3d7823a77aa) | `` ci/eval: add rebuildsByPlatform to the comparison result ``                                  |
| …

chore(flake/nixpkgs): `4633a7c7` -> `5d67ea6b`

---

flake.lock

| Commit                                                                                         | Message                                                                             |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`77306ff5`](https://github.com/NixOS/nixpkgs/commit/77306ff547b51e819ba617b140bb355e1d719f31) | `` chore(mergify): remove not relevant Tag check (#365804) ``                       |
| [`e5d90d92`](https://github.com/NixOS/nixpkgs/commit/e5d90d92ae07e4843dcc5a4d8195ec29c96d8e4d) | `` python312Packages.llama-index-multi-modal-llms-openai: 0.3.0 -> 0.4.0 ``         |
| …

chore(flake/nixpkgs): `5d67ea6b` -> `d3c42f18`

---

flake.lock

| Commit                                                                                           | Message                                                                            |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------- |
| [`2b01a5bc`](https://github.com/hyprwm/Hyprland/commit/2b01a5bcf62956a5d641a3367edcd35e103edfcd) | `` xwayland: don't create an abstract unix domain socket on linux (#8874) ``       |
| [`8d4c18d7`](https://github.com/hyprwm/Hyprland/commit/8d4c18d723d18f5bf5190b62b562301860df74f7) | `` core: refactor/improve monitor mode selection (#8804) ``                        |
| …

chore(flake/hyprland): `31422ae2` -> `2b01a5bc`

---

flake.lock

| Commit                                                                                         | Message                                                                                              |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------- |
| [`055ed209`](https://github.com/NixOS/nixpkgs/commit/055ed2091b3ebfc88c898d3d68ab873387a5ce8b) | `` nixosTests.gitlab: do not block nixos-unstable on aarch64 ``                                      |
| [`c847ffcb`](https://github.com/NixOS/nixpkgs/commit/c847ffcbe3014c58afe6f20da8b349606e276553) | `` terraform-providers.acme: 2.28.2 -> 2.29.0 `` …

chore(flake/nixpkgs): `d3c42f18` -> `634fd468`

---

flake.lock

| Commit                                                                                           | Message                                                                               |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------- |
| [`1989b004`](https://github.com/hyprwm/Hyprland/commit/1989b0049f7fb714a2417dfb14d6b4f3d2a079d3) | `` hyprpm: add glaze dependency FetchContent fallback (#8899) ``                      |
| [`9f933da1`](https://github.com/hyprwm/Hyprland/commit/9f933da1c502989cadf7696971aa376d65847b95) | `` renderer: fix oversized blur precalcs not blurring at all ``                       |
| …

chore(flake/hyprland): `2b01a5bc` -> `1989b004`

---

flake.lock

| Commit                                                                                         | Message                                                                                     |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- |
| [`11bbeb48`](https://github.com/NixOS/nixpkgs/commit/11bbeb48fb07a6d67c36303641fdfd614f7fda18) | `` pylyzer: 0.0.75 -> 0.0.76 ``                                                             |
| [`42e57dec`](https://github.com/NixOS/nixpkgs/commit/42e57decdf4da8a2ba57c690b56a9771900a2b2d) | `` paper-clip: fix compilation error caused by glib ``                                      |
| …

chore(flake/nixpkgs): `634fd468` -> `88195a94`

---

flake.lock

| Commit                                                                                         | Message                                                                   |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------- |
| [`1d5cb8a3`](https://github.com/NixOS/nixpkgs/commit/1d5cb8a3330cbc7f323177591672fc6f1a31cae1) | `` pretix: fix tests after 2025-01-01 ``                                  |
| [`c4d943e9`](https://github.com/NixOS/nixpkgs/commit/c4d943e9eed5b3d717ae70289e440c4a22976630) | `` perlPackages.Testutf8: fix homepage ``                                 |
| [`1f3d0b2d`](https://github.com/NixOS/nixpkgs/commit/1f3d0b2d471358a782b8fe5779d0e37e4f4e0903) | …

chore(flake/nixpkgs): `88195a94` -> `8f3e1f80`

---

flake.lock

| Commit                                                                                           | Message                                                                                       |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------- |
| [`25add268`](https://github.com/hyprwm/Hyprland/commit/25add26881d7b98d2b80eb7a95d3aee0449b72b9) | `` renderer: unload background texture if it's disabled ``                                    |
| [`f16f1704`](https://github.com/hyprwm/Hyprland/commit/f16f170433540d85cf672217bca2d64c6db9eb01) | `` protocols: immediately copy toplevel content when ignoreDamage set (#9049) ``              |
| …

chore(flake/hyprland): `67e1e46f` -> `25add268`

---

flake.lock

| Commit                                                                                         | Message                                                                                        |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| [`01c1ec8f`](https://github.com/NixOS/nixpkgs/commit/01c1ec8f5fb4c95653afe0984df9bd9a948286d1) | `` osmium-tool: fix build ``                                                                   |
| [`2686ec7e`](https://github.com/NixOS/nixpkgs/commit/2686ec7e75c3912056075a83d50079b3ebeb5cd1) | `` xilinx-bootgen: xilinx_v2024.1 -> xilinx_v2024.2 ``                                         |
| …

chore(flake/nixpkgs): `8f3e1f80` -> `9abb87b5`
