NeonGamerBot-QK/nixos

- flake.lock
| [`1cb26887`](https://github.com/nix-community/NUR/commit/1cb268872ecbbb8bcdd76937b1f7536de880811b) | `` automatic update `` |
| [`e2421890`](https://github.com/nix-community/NUR/commit/e2421890776434256d3f26e4684096cb44becea3) | `` automatic update `` |
| [`da5ae2ff`](https://github.com/nix-community/NUR/commit/da5ae2ffb6f4c7f56ce9a096339f7d953c527428) | `` automatic update `` |
| [`f72f677c`](https://github.com/nix-community/NUR/commit/f72f677c3064fdc20991610a3e990c5de0dc12e7) | `` automatic update `` |
| …
> chore(flake/nur): `ee7ba7bc` -> `1cb26887`

- flake.lock
| [`1a9ad3e4`](https://github.com/nix-community/nix-vscode-extensions/commit/1a9ad3e44ca93a0167dad66444443d7e8ee7bb3a) | `` action `` |
| [`fb86a415`](https://github.com/nix-community/nix-vscode-extensions/commit/fb86a415579cd38eb7b47c3ada597841b97e2ea9) | `` action `` |
| [`487e99ff`](https://github.com/nix-community/nix-vscode-extensions/commit/487e99ffa42d57de53eba5ca4b60cd95fb442c42) | `` action `` |
| [`de538d22`](https://github.com/nix-community/nix-vscode-extensions/commit/de538d220bccc69ad940a53e2b50fef7e05501f2) …
> chore(flake/nix-vscode-extensions): `8822dcf9` -> `1a9ad3e4`

- flake.lock
| Commit                                                                                                | Message                                                |
| ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`2f429398`](https://github.com/Gerg-L/spicetify-nix/commit/2f429398aef267d98858ca98d2f2a38a8ee90fb3) | `` Bump actions/checkout from 4.1.7 to 4.2.0 (#231) `` |
| [`12818daa`](https://github.com/Gerg-L/spicetify-nix/commit/12818daad07217189b0f7a9203c0000040c8a6e4) | `` CI update 2024-09-26 ``                             |
| [`863ec9bd`](https://github.com/Gerg-L/spicetify-nix/commit/863ec9bd1dcd383c4a22551ccb29234a73f094c8) | `` CI update 2024-09-25 `` …
> chore(flake/spicetify-nix): `dae2f769` -> `2f429398`

- flake.lock
| [`c0df2f7c`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/c0df2f7c4d84b5a0e0c2937824139f4fd16c6d5c) | `` Update Ruby versions `` |
> chore(flake/nixpkgs-ruby): `291a8030` -> `c7a557d4`

- flake.lock
| [`40322094`](https://github.com/nix-community/NUR/commit/4032209447299ce63b218596bd01d51914c3c1f4) | `` automatic update `` |
> chore(flake/nur): `118b6b0b` -> `40322094`

- flake.lock
| Commit                                                                                           | Message                  |
| ------------------------------------------------------------------------------------------------ | ------------------------ |
| [`58669fef`](https://github.com/hyprwm/Hyprland/commit/58669fef77ac17ea205ce3570f48e17de736111f) | `` flake.lock: update `` |
> chore(flake/hyprland): `e20aef7d` -> `58669fef`

- flake.lock
| [`90646627`](https://github.com/nix-community/NUR/commit/90646627b3b6815c4ecb4c11b85b0b0c050b717a) | `` automatic update `` |
| [`568c8955`](https://github.com/nix-community/NUR/commit/568c89559ad9d8677e801690bf8e74472823d806) | `` automatic update `` |
> chore(flake/nur): `09b6fea7` -> `90646627`

- flake.lock
| [`78754dc9`](https://github.com/nix-community/NUR/commit/78754dc9109a515ada22055526af4954237ee650) | `` automatic update `` |
> chore(flake/nur): `90646627` -> `78754dc9`

- flake.lock
| [`bb4818cf`](https://github.com/nix-community/NUR/commit/bb4818cf574dcabcc29fbcb48b43339187a5d5cb) | `` automatic update `` |
| [`07529709`](https://github.com/nix-community/NUR/commit/075297092687faea7056606059429e977ef48410) | `` automatic update `` |
| [`774cef87`](https://github.com/nix-community/NUR/commit/774cef87e69dc210fba4b6abcd6079f24ed323f5) | `` automatic update `` |
| [`0a8ea00e`](https://github.com/nix-community/NUR/commit/0a8ea00e4d122c12f2abb4a9a9b3bb94f1a99427) | `` automatic update `` |
| …
> chore(flake/nur): `58b501ea` -> `bb4818cf`

- flake.lock
| [`4d9f4dce`](https://github.com/nix-community/NUR/commit/4d9f4dcec2598c8cf6878522b69e230086c2175a) | `` automatic update `` |
| [`c393c285`](https://github.com/nix-community/NUR/commit/c393c2856e06a8b50b06111286ecf3f18fc834c9) | `` automatic update `` |
| [`302e013d`](https://github.com/nix-community/NUR/commit/302e013d8945f9b1f9253b1d05c9a0a09f975428) | `` automatic update `` |
| [`4759e62e`](https://github.com/nix-community/NUR/commit/4759e62e92bf3543846cc3c79da58a275092938a) | `` automatic update `` |
| …
> chore(flake/nur): `01c22fb0` -> `4d9f4dce`

- flake.lock
| [`0773b6dd`](https://github.com/nix-community/NUR/commit/0773b6dd4cb24ce2538430344a874f0f32863e2a) | `` automatic update `` |
| [`0feb77e8`](https://github.com/nix-community/NUR/commit/0feb77e8ad83cf9109fc05c44a978bf1af3520a4) | `` automatic update `` |
| [`adb55544`](https://github.com/nix-community/NUR/commit/adb555447eae28078977e194a4ea2a61fed0c01a) | `` automatic update `` |
| [`5cf5605c`](https://github.com/nix-community/NUR/commit/5cf5605cb2630639a716450161e0bba47bd439f4) | `` automatic update `` |
| …
> chore(flake/nur): `4d9f4dce` -> `0773b6dd`

- flake.lock
| [`9d9bcd30`](https://github.com/nix-community/NUR/commit/9d9bcd30fec126b08b49020b7af08bc1aad66210) | `` automatic update `` |
| [`1a658320`](https://github.com/nix-community/NUR/commit/1a6583200877cbbc9b64a5cd2b1fc9b93553ec65) | `` automatic update `` |
| [`66999725`](https://github.com/nix-community/NUR/commit/6699972587a34e38a7328d493d3b75ea393de5f9) | `` automatic update `` |
| [`d311aa67`](https://github.com/nix-community/NUR/commit/d311aa6727603c65ab87a068099f136bf4b6f194) | `` automatic update `` |
| …
> chore(flake/nur): `0773b6dd` -> `9d9bcd30`

- flake.lock
| Commit                                                                                           | Message                                                                |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------- |
| [`de68e065`](https://github.com/hyprwm/Hyprland/commit/de68e065fe861d7ca01eca267df4c305bc6e73c2) | `` layout: fix dragging a window into a group after e242694 (#7976) `` |
> chore(flake/hyprland): `e2426942` -> `de68e065`

- flake.lock
| Commit                                                                                                | Message                     |
| ----------------------------------------------------------------------------------------------------- | --------------------------- |
| [`b9bf3717`](https://github.com/Gerg-L/spicetify-nix/commit/b9bf3717400d579a2074fb4067d761bb1b1c07d5) | `` Add Hazy theme (#232) `` |
> chore(flake/spicetify-nix): `3e033244` -> `b9bf3717`

- flake.lock
| [`6618c358`](https://github.com/nix-community/nix-vscode-extensions/commit/6618c358b44a779a379485177d3391e9bd32fa09) | `` action `` |
> chore(flake/nix-vscode-extensions): `718a9b94` -> `6618c358`

- flake.lock
| [`829a8104`](https://github.com/Gerg-L/spicetify-nix/commit/829a81049fb019d12be8daf867c03de2ee52d49f) | `` CI update 2024-10-03 `` |
> chore(flake/spicetify-nix): `b9bf3717` -> `829a8104`

- flake.lock
| [`dc8cf1e9`](https://github.com/nix-community/NUR/commit/dc8cf1e9b9af7a15d6ab68790f0c463cd8824fe4) | `` automatic update `` |
| [`1f6b9a4c`](https://github.com/nix-community/NUR/commit/1f6b9a4c9cf2f7d8af7040e7f8fceeba2690c76d) | `` automatic update `` |
| [`0c800912`](https://github.com/nix-community/NUR/commit/0c800912c07bd05851b69850e10e59b48da07280) | `` automatic update `` |
| [`28edb8a6`](https://github.com/nix-community/NUR/commit/28edb8a6f0d93bceb50730e642fb77986f858892) | `` automatic update `` |
| …
> chore(flake/nur): `9d9bcd30` -> `dc8cf1e9`

- flake.lock
| [`2eaa6a4b`](https://github.com/nix-community/NUR/commit/2eaa6a4b8f589bc82805ec76506e9264e3acec9a) | `` automatic update `` |
| [`47d63dca`](https://github.com/nix-community/NUR/commit/47d63dcaa78c3b29d0fecc96f07a0103d7a94f1d) | `` automatic update `` |
| [`5c4eb392`](https://github.com/nix-community/NUR/commit/5c4eb392ae4579a79bb2f9b72ae3465a842b3a92) | `` automatic update `` |
| [`5eaecb7d`](https://github.com/nix-community/NUR/commit/5eaecb7dad579d5b9a93252adbc38fa02e3aa22d) | `` automatic update `` |
| …
> chore(flake/nur): `dc8cf1e9` -> `2eaa6a4b`

- flake.lock
| Commit                                                                                                        | Message                                              |
| ------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`d0d66dbf`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/d0d66dbf096ebe266a19027717c7f3660306f195) | `` Update cachix/install-nix-action action to v30 `` |
> chore(flake/nixpkgs-ruby): `1e91d8b4` -> `afa70833`

- flake.lock
| [`74808acd`](https://github.com/nix-community/NUR/commit/74808acd5ce51758868b42eaedc8a608c3006c73) | `` automatic update `` |
| [`11606883`](https://github.com/nix-community/NUR/commit/116068830b5fdc6aef13d4b2dc2d4f1c6a826326) | `` automatic update `` |
| [`f74e49cf`](https://github.com/nix-community/NUR/commit/f74e49cf480cc13f23fe79f476720c44e9bda1a2) | `` automatic update `` |
| [`a84320ef`](https://github.com/nix-community/NUR/commit/a84320efa71376f5a7e77e5736e81e64d8c32488) | `` automatic update `` |
| …
> chore(flake/nur): `18f1593e` -> `74808acd`

- flake.lock
| [`0df7de2c`](https://github.com/nix-community/NUR/commit/0df7de2ca7fe908506a78442b688ef254d5de3e0) | `` automatic update `` |
| [`b638dbc3`](https://github.com/nix-community/NUR/commit/b638dbc3cd5ecae15140d2de7897dc9395cd128e) | `` automatic update `` |
| [`c618676f`](https://github.com/nix-community/NUR/commit/c618676f7584437c78c91561baf50281181de20c) | `` automatic update `` |
| [`049aa045`](https://github.com/nix-community/NUR/commit/049aa045d7bb0ce32734eca872c8725b5d95a6d4) | `` automatic update `` |
| …
> chore(flake/nur): `74808acd` -> `0df7de2c`

- flake.lock
| [`277107c2`](https://github.com/Gerg-L/spicetify-nix/commit/277107c2bc07582899d53e7fc901e93126d944bd) | `` CI update 2024-10-05 `` |
> chore(flake/spicetify-nix): `1389b984` -> `277107c2`

- flake.lock
| [`43482ab1`](https://github.com/nix-community/nix-vscode-extensions/commit/43482ab1bc35a4cf504d078771804f181c15293c) | `` action `` |
> chore(flake/nix-vscode-extensions): `fafbff41` -> `43482ab1`

- flake.lock
| [`a62be009`](https://github.com/nix-community/NUR/commit/a62be00984c8eb457368bda73fa0c24949360743) | `` automatic update `` |
| [`7090c452`](https://github.com/nix-community/NUR/commit/7090c452983a90c066ce421bb75eaa0409f45910) | `` automatic update `` |
| [`872ace6c`](https://github.com/nix-community/NUR/commit/872ace6c6443f6d7137962c761d529df75610137) | `` automatic update `` |
| [`07825573`](https://github.com/nix-community/NUR/commit/07825573f031d8ea3d93f538202383c793c8e40e) | `` automatic update `` |
| …
> chore(flake/nur): `0df7de2c` -> `a62be009`

- flake.lock
| Commit                                                                                           | Message                                                   |
| ------------------------------------------------------------------------------------------------ | --------------------------------------------------------- |
| [`4e41cda2`](https://github.com/hyprwm/Hyprland/commit/4e41cda27ed4176005082436cb35878335e63fae) | `` security-context: close client fds after disconnect `` |
| [`da86aac0`](https://github.com/hyprwm/Hyprland/commit/da86aac0f5c5c3604351961b901f62cdf7186a10) | `` security-context: implement protocol ``                |
> chore(flake/hyprland): `0c7a7e2d` -> `4e41cda2`

- flake.lock
| [`57c2b57d`](https://github.com/nix-community/NUR/commit/57c2b57d5f69956d3358ac9a839b6a9c24ad9821) | `` automatic update `` |
| [`cd1d2ddc`](https://github.com/nix-community/NUR/commit/cd1d2ddc7f926c4a0f4373bf06c1a46fac4c233c) | `` automatic update `` |
| [`5cc3dd44`](https://github.com/nix-community/NUR/commit/5cc3dd44039b1aae38ba8c765634a54e6ce43ae0) | `` automatic update `` |
| [`6c43cdee`](https://github.com/nix-community/NUR/commit/6c43cdee3fb69a31ee007a94fab07d18d813efda) | `` automatic update `` |
| …
> chore(flake/nur): `e6ad3593` -> `57c2b57d`

- flake.lock
| Commit                                                                                             | Message                                            |
| -------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`7953d66c`](https://github.com/nix-community/NUR/commit/7953d66ccc90bf2036416609879eb38e684b6948) | `` automatic update ``                             |
| [`4a361eda`](https://github.com/nix-community/NUR/commit/4a361eda743e2183bf9cd4d9778e326437b88ebe) | `` automatic update ``                             |
| [`e7902d00`](https://github.com/nix-community/NUR/commit/e7902d008045cab316f6da30616a92cb18867f85) | `` automatic update ``                             |
| …
> chore(flake/nur): `57c2b57d` -> `7953d66c`

- flake.lock
| [`4bcc76b9`](https://github.com/Gerg-L/spicetify-nix/commit/4bcc76b94f01cfddc899191e99d96059b8702608) | `` CI update 2024-10-07 `` |
> chore(flake/spicetify-nix): `f532f68a` -> `4bcc76b9`

- flake.lock
| [`e0ffefe0`](https://github.com/nix-community/NUR/commit/e0ffefe0ffe92d2fbd499ae6628df88b652b9540) | `` automatic update `` |
| [`fbcfc133`](https://github.com/nix-community/NUR/commit/fbcfc133e79aaf4b39acc37a827c84c3605ad0aa) | `` automatic update `` |
| [`ddc2c6a3`](https://github.com/nix-community/NUR/commit/ddc2c6a3485c58aa902bf15c181bd9675189f272) | `` automatic update `` |
| [`bda6fb38`](https://github.com/nix-community/NUR/commit/bda6fb38a7cf14cfb63d343efde7fdb83cbf528f) | `` automatic update `` |
| …
> chore(flake/nur): `7953d66c` -> `e0ffefe0`

- flake.lock
| [`e4a8bb0b`](https://github.com/nix-community/NUR/commit/e4a8bb0b7deb52e99e9dd2bdfc29580b346bf69d) | `` automatic update `` |
| [`7fc13fc5`](https://github.com/nix-community/NUR/commit/7fc13fc5ea634482f96525f06132646d5aa01f7f) | `` automatic update `` |
| [`c8a07068`](https://github.com/nix-community/NUR/commit/c8a0706891368a9243fcb8474ebe162c9ea1fcd6) | `` automatic update `` |
| [`f5694462`](https://github.com/nix-community/NUR/commit/f5694462fd4654504660d882a36280b075e77ce2) | `` automatic update `` |
| …
> chore(flake/nur): `e0ffefe0` -> `e4a8bb0b`

- flake.lock
| Commit                                                                                           | Message                                                                       |
| ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------- |
| [`e0cfbec6`](https://github.com/hyprwm/Hyprland/commit/e0cfbec66b97edb2957508152f32e77a1b181afc) | `` keybinds: fixup xkb_states for resolve_by_sym ``                           |
| [`b3a7e310`](https://github.com/hyprwm/Hyprland/commit/b3a7e3109bf2b7b4422424471130197dc08baeb1) | `` misc: refactor version command (#8027) ``                                  |
| [`45e82199`](https://github.com/hyprwm/Hyprland/commit/45e82199fb29f422ebb …
> chore(flake/hyprland): `0d70c442` -> `e0cfbec6`

- flake.lock
| [`84fa538b`](https://github.com/nix-community/NUR/commit/84fa538b856ea6e076ae21c3eddff91a537374e2) | `` automatic update `` |
| [`854a676d`](https://github.com/nix-community/NUR/commit/854a676df29bb977182b7bc63ed3ab6a0f820b06) | `` automatic update `` |
| [`21e1688c`](https://github.com/nix-community/NUR/commit/21e1688c47a3d33a47159352236a9176fdefb507) | `` automatic update `` |
| [`519d71b2`](https://github.com/nix-community/NUR/commit/519d71b2a8e091eac8934392d17439f8eadef7c1) | `` automatic update `` |
| …
> chore(flake/nur): `e4a8bb0b` -> `84fa538b`

- flake.lock
| [`85ca2b37`](https://github.com/Gerg-L/spicetify-nix/commit/85ca2b370f962f81973443adb31f2e3559eda1dd) | `` CI update 2024-10-09 `` |
> chore(flake/spicetify-nix): `194e9bb7` -> `85ca2b37`

- flake.lock
| Commit                                                                                           | Message                                                        |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------------------- |
| [`6ae89940`](https://github.com/hyprwm/Hyprland/commit/6ae89940c761d4ed4317df0af29e8df41d472091) | `` layout: add merge_floated_into_tiled_on_groupbar (#8042) `` |
| [`3d28879c`](https://github.com/hyprwm/Hyprland/commit/3d28879c2640cdb6e8426127692240100793bfef) | `` hyprerror: fix height calc with bottom bar (#8043) ``       |
| [`223dcc8b`](https://github.com/hyprwm/Hyprland/commit/223dcc8bac7fee90aa6aa7596d9379e56b526e62) | `` output: update state even if no …
> chore(flake/hyprland): `bc299928` -> `6ae89940`

- flake.lock
| [`3fce8e9b`](https://github.com/nix-community/NUR/commit/3fce8e9b3b18bc6e599dd439d5c9973c6e63438c) | `` automatic update `` |
| [`9877180a`](https://github.com/nix-community/NUR/commit/9877180a34218c43f504018c7d0dc2b9e4062a91) | `` automatic update `` |
| [`61ba1d05`](https://github.com/nix-community/NUR/commit/61ba1d0514cc732cd0079a33d3b605d836600503) | `` automatic update `` |
| [`ca209137`](https://github.com/nix-community/NUR/commit/ca209137ba2927dc135fe8e25f004eb147e4fe46) | `` automatic update `` |
| …
> chore(flake/nur): `84fa538b` -> `3fce8e9b`

- flake.lock
| Commit                                                                                           | Message                                     |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------- |
| [`c4eb1940`](https://github.com/hyprwm/Hyprland/commit/c4eb1940336cd88ca65ba65582ce104e49dfc7c9) | `` gammactrl: guard pMonitor in setGamma `` |
> chore(flake/hyprland): `6ae89940` -> `c4eb1940`

- flake.lock
| Commit                                                                                                        | Message                                            |
| ------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [`c37a4b30`](https://github.com/bobvanderlinden/nixpkgs-ruby/commit/c37a4b30a150b4e7e9deff18d5ff674cfaa94be1) | `` README: suggest git add after using template `` |
> chore(flake/nixpkgs-ruby): `08c66f1d` -> `2337dcf3`

- flake.lock
| [`d6e8bdf8`](https://github.com/Gerg-L/spicetify-nix/commit/d6e8bdf856dfba9f704fd58df4c865be8d819b30) | `` CI update 2024-10-10 `` |
> chore(flake/spicetify-nix): `85ca2b37` -> `d6e8bdf8`

- flake.lock
| Commit                                                                                           | Message                                          |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| [`b65773be`](https://github.com/hyprwm/Hyprland/commit/b65773bea9b912a41cfcbc789fb2e60a07e3d0c1) | `` hyprpm: disallow shallow on unknown branch `` |
> chore(flake/hyprland): `c4eb1940` -> `b65773be`

- flake.lock
| [`0eb5a0ee`](https://github.com/nix-community/NUR/commit/0eb5a0ee12c355e8e897e0fe23e1ff9df332a9a6) | `` automatic update `` |
| [`61e853a9`](https://github.com/nix-community/NUR/commit/61e853a9915313fe85f7900187d1878170c4780b) | `` automatic update `` |
| [`666ee000`](https://github.com/nix-community/NUR/commit/666ee000c48626633f3835abd8a40c558fb0b00e) | `` automatic update `` |
| [`5ec541fb`](https://github.com/nix-community/NUR/commit/5ec541fb7b2b8858e8c4c1aa96bfb4bf7f52f83b) | `` automatic update `` |
| …
> chore(flake/nur): `202de6e5` -> `0eb5a0ee`

- flake.lock
| Commit                                                                                                      | Message                                             |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`2b13611e`](https://github.com/nix-community/home-manager/commit/2b13611eaed8326789f76f70d21d06fbb14e3e47) | `` floorp: add module ``                            |
| [`65ae9c14`](https://github.com/nix-community/home-manager/commit/65ae9c147349829d3df0222151f53f79821c5134) | `` git: add module for `git maintenance` (#5772) `` |
> chore(flake/home-manager): `58283095` -> `2b13611e`

- flake.lock
| [`75a800a7`](https://github.com/nix-community/NUR/commit/75a800a7f85d9518c12db18993ea5271577062f6) | `` automatic update `` |
| [`f6cf2b59`](https://github.com/nix-community/NUR/commit/f6cf2b5901939fda6688f7d6e0ea885da84d90c0) | `` automatic update `` |
| [`3a66f1df`](https://github.com/nix-community/NUR/commit/3a66f1df4434cadcd7811bfeae3866ed8d4dfbf2) | `` automatic update `` |
| [`7bdbe275`](https://github.com/nix-community/NUR/commit/7bdbe27588a3338324806750628048d2e5f68f35) | `` automatic update `` |
| …
> chore(flake/nur): `1d874e69` -> `75a800a7`

- flake.lock
| [`f4b5dd4b`](https://github.com/nix-community/NUR/commit/f4b5dd4bba09018564cbf60ddb4bdd5b5784e869) | `` automatic update `` |
| [`fbcb5c26`](https://github.com/nix-community/NUR/commit/fbcb5c26f0df361b4e041d04dc604ea03de9b0df) | `` automatic update `` |
| [`a7f781cd`](https://github.com/nix-community/NUR/commit/a7f781cd4052a3a0c118ca743bc1b5a6bf8bd15e) | `` automatic update `` |
| [`b6c2b87b`](https://github.com/nix-community/NUR/commit/b6c2b87bad3234f930d3880ec23f96bb62842fc7) | `` automatic update `` |
| …
> chore(flake/nur): `c6b7ef33` -> `f4b5dd4b`

- flake.lock
| [`1f3c6931`](https://github.com/Gerg-L/spicetify-nix/commit/1f3c6931100c64f6747d47f8a7b8d7a75fc5844e) | `` CI update 2024-10-13 `` |
> chore(flake/spicetify-nix): `59aa5259` -> `1f3c6931`

- flake.lock
| [`95bfc761`](https://github.com/nix-community/NUR/commit/95bfc76150c171d0a73d0e4437904c844259ecce) | `` automatic update `` |
| [`e59d2d99`](https://github.com/nix-community/NUR/commit/e59d2d9966013844ccc306daf30db36fa32397b8) | `` automatic update `` |
| [`09a63588`](https://github.com/nix-community/NUR/commit/09a6358819708273c6406a0f0bfd640038aaa9c0) | `` automatic update `` |
| [`2c40a022`](https://github.com/nix-community/NUR/commit/2c40a022a3b3b0d981909a18b59887bd7abfcaa3) | `` automatic update `` |
| …
> chore(flake/nur): `905c6c98` -> `95bfc761`

- flake.lock
| [`c3463a84`](https://github.com/Gerg-L/spicetify-nix/commit/c3463a8497fef3150aa8635d32b61b16e17a1e6b) | `` CI update 2024-10-14 `` |
> chore(flake/spicetify-nix): `1f3c6931` -> `c3463a84`

- flake.lock
| [`64079c91`](https://github.com/nix-community/NUR/commit/64079c912fb1734bf1f06ba4754ae8a1b6fa6e25) | `` automatic update `` |
| [`2476177b`](https://github.com/nix-community/NUR/commit/2476177b9e2bb9cde1393c928ba58574d6b6d78f) | `` automatic update `` |
| [`edbc15b9`](https://github.com/nix-community/NUR/commit/edbc15b9f52972a4d95545db61f093295bfb7612) | `` automatic update `` |
| [`da1c520a`](https://github.com/nix-community/NUR/commit/da1c520a9acd9a9d1402db1939c9b9a2fa49b4b8) | `` automatic update `` |
| …
> chore(flake/nur): `95bfc761` -> `64079c91`

- flake.lock
| [`afbdf987`](https://github.com/nix-community/nix-vscode-extensions/commit/afbdf987e8613d980e3ae20c552b76fa2d7f6df4) | `` action `` |
> chore(flake/nix-vscode-extensions): `1238ef47` -> `afbdf987`

- flake.lock
| [`81a5fdad`](https://github.com/nix-community/nix-vscode-extensions/commit/81a5fdadd8b5b473d8a51a6ec751c94ed180707e) | `` action `` |
> chore(flake/nix-vscode-extensions): `afbdf987` -> `81a5fdad`

- flake.lock
| [`7aafd5f0`](https://github.com/nix-community/NUR/commit/7aafd5f0d772efbd2e611c132cc290c3508fe049) | `` automatic update `` |
| [`f3716d0b`](https://github.com/nix-community/NUR/commit/f3716d0b1c0df0ed7306b2138544b55e31532c18) | `` automatic update `` |
| [`4286457d`](https://github.com/nix-community/NUR/commit/4286457de873ab04f746921c2205b5044e5c713a) | `` automatic update `` |
| [`c7aa97cf`](https://github.com/nix-community/NUR/commit/c7aa97cf84cdc4fcd926db3c41a6471444a2a542) | `` automatic update `` |
| …
> chore(flake/nur): `64079c91` -> `7aafd5f0`

- flake.lock
| [`f4dd6d6b`](https://github.com/nix-community/nix-vscode-extensions/commit/f4dd6d6b728a61095b944de1fbc58c5bbdc87320) | `` action `` |
> chore(flake/nix-vscode-extensions): `a2a26f1b` -> `f4dd6d6b`

- flake.lock
| [`1a8fa34b`](https://github.com/Gerg-L/spicetify-nix/commit/1a8fa34b656d67c1d7d4c2b76cba03bf4d65dee4) | `` CI update 2024-10-20 `` |
| [`3dd5c8c3`](https://github.com/Gerg-L/spicetify-nix/commit/3dd5c8c33ee1b8d20d855e9fa425361719931b04) | `` CI update 2024-10-19 `` |
| [`095be8b3`](https://github.com/Gerg-L/spicetify-nix/commit/095be8b3a9bb9ec14cbe67cc4710f5e224639da5) | `` CI update 2024-10-18 `` |
| [`f5bb3bd8`](https://github.com/Gerg-L/spicetify-nix/commit/f5bb3bd8cb92ee6a37510be477cbfb2fd6a682c1) | `` CI update …
> chore(flake/spicetify-nix): `a83d478b` -> `1a8fa34b`

- flake.lock
| Commit                                                                                             | Message                       |
| -------------------------------------------------------------------------------------------------- | ----------------------------- |
| [`fdda8034`](https://github.com/nix-community/NUR/commit/fdda803471577189005bac0b4bc934689f52ef59) | `` automatic update ``        |
| [`a05b041f`](https://github.com/nix-community/NUR/commit/a05b041fff7a2e4872d361dc03025d0f4cadb2f6) | `` automatic update ``        |
| [`3dcac521`](https://github.com/nix-community/NUR/commit/3dcac521b838af86206d66a8ebbc82967844ee96) | `` automatic update ``        |
| [`34b3a8ab`](https://github.com/nix-community/NUR/commit/34b3a8ab784a61c73fc60d8d3436b37095264519) | `` automatic update …
> chore(flake/nur): `7aafd5f0` -> `fdda8034`

- flake.lock
| [`7dcfbba6`](https://github.com/Gerg-L/spicetify-nix/commit/7dcfbba64faedd15574e6df5d89b2bcf5bb20128) | `` CI update 2024-10-21 `` |
> chore(flake/spicetify-nix): `1a8fa34b` -> `7dcfbba6`

- flake.lock
| [`77a421d6`](https://github.com/nix-community/nix-vscode-extensions/commit/77a421d6c7ea09381c7e33d90c3017c9727dfbc3) | `` action `` |
> chore(flake/nix-vscode-extensions): `f4dd6d6b` -> `77a421d6`

- flake.lock
| [`f4de2a37`](https://github.com/nix-community/NUR/commit/f4de2a37f42dfc323d264f2cd01cdf296dd8d58e) | `` automatic update `` |
| [`41ca6cfe`](https://github.com/nix-community/NUR/commit/41ca6cfe238fdfab2831386c5a65f5c0a01e1cfd) | `` automatic update `` |
| [`fac95d00`](https://github.com/nix-community/NUR/commit/fac95d00bc5477e1ff720a5fed93b58e896dc9d0) | `` automatic update `` |
| [`bc99c38a`](https://github.com/nix-community/NUR/commit/bc99c38ac253f06eb3a634284703fdf5d40b5133) | `` automatic update `` |
| …
> chore(flake/nur): `fdda8034` -> `f4de2a37`

- flake.lock
| [`715ee6f5`](https://github.com/nix-community/NUR/commit/715ee6f5810e4fa24e8974aa21eef99efd083efb) | `` automatic update `` |
| [`8fb246dd`](https://github.com/nix-community/NUR/commit/8fb246ddebad951fc4f237d0716b941a18405d50) | `` automatic update `` |
| [`dc963a13`](https://github.com/nix-community/NUR/commit/dc963a131530e44982b646447c7e54b376d23e09) | `` automatic update `` |
| [`9009303f`](https://github.com/nix-community/NUR/commit/9009303f43b03a29212dfabcebb10e4d04855b6a) | `` automatic update `` |
| …
> chore(flake/nur): `f4de2a37` -> `715ee6f5`

- flake.lock
| [`ba02ecf1`](https://github.com/nix-community/nix-vscode-extensions/commit/ba02ecf164ec8da6f4d33d1f1e270b4a84252d60) | `` action `` |
> chore(flake/nix-vscode-extensions): `77a421d6` -> `ba02ecf1`

- flake.lock
| [`96cf0aad`](https://github.com/Gerg-L/spicetify-nix/commit/96cf0aad6fe67a31567a51e54dc6b9fcbe90626a) | `` CI update 2024-10-22 `` |
> chore(flake/spicetify-nix): `7dcfbba6` -> `96cf0aad`

- flake.lock
| Commit                                                                                           | Message                                            |
| ------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| [`2b6ff683`](https://github.com/hyprwm/Hyprland/commit/2b6ff6837e81a3b459f2f3cc366830c420a7a62e) | `` groups: add group_on_movetoworkspace (#8159) `` |
| [`29997ef4`](https://github.com/hyprwm/Hyprland/commit/29997ef4ba8ef0a80390e80199998d1390177454) | `` default/config: improve default animations ``   |
> chore(flake/hyprland): `5e96d738` -> `2b6ff683`

- flake.lock
| [`0c8e15ab`](https://github.com/nix-community/NUR/commit/0c8e15ab944d0f2a3af6472736163efa496878cf) | `` automatic update `` |
| [`6fdfad15`](https://github.com/nix-community/NUR/commit/6fdfad15c101c77c24df6039a8849e0f27440098) | `` automatic update `` |
| [`a0e7acae`](https://github.com/nix-community/NUR/commit/a0e7acae5a9433fca059ee5c630c9a50afc32e17) | `` automatic update `` |
| [`7f29a363`](https://github.com/nix-community/NUR/commit/7f29a363a1b01b5751a45335fa867101a19e433a) | `` automatic update `` |
| …
> chore(flake/nur): `715ee6f5` -> `0c8e15ab`

- flake.lock
| [`b9d88696`](https://github.com/Gerg-L/spicetify-nix/commit/b9d886969141231ca687a915a2c33b3e85c3085c) | `` CI update 2024-10-23 `` |
> chore(flake/spicetify-nix): `96cf0aad` -> `b9d88696`

- flake.lock
| [`b7983725`](https://github.com/nix-community/NUR/commit/b79837253f7eb49c14d8665b656202ef0d78845a) | `` automatic update `` |
| [`0d6deafa`](https://github.com/nix-community/NUR/commit/0d6deafafa3026810e12334ddc9c483b27c8069b) | `` automatic update `` |
| [`88ecc6b9`](https://github.com/nix-community/NUR/commit/88ecc6b91c387be529b4bb36fc376858fd6df278) | `` automatic update `` |
| [`0afe3561`](https://github.com/nix-community/NUR/commit/0afe356132e7d910888d17237c84fba13057e355) | `` automatic update `` |
| …
> chore(flake/nur): `0c8e15ab` -> `b7983725`

- flake.lock
| Commit                                                                                           | Message                  |
| ------------------------------------------------------------------------------------------------ | ------------------------ |
| [`6e0aadc5`](https://github.com/hyprwm/Hyprland/commit/6e0aadc585c6d9fdaaebfa5853adbf9610897c82) | `` updated flake.lock `` |
> chore(flake/hyprland): `2b6ff683` -> `6e0aadc5`

- flake.lock
| [`20a5ac55`](https://github.com/nix-community/NUR/commit/20a5ac55687e9c19d3965387d89dd1ae1449af80) | `` automatic update `` |
| [`cdc7e2f7`](https://github.com/nix-community/NUR/commit/cdc7e2f7c999caf34a9f1b937efb79e9504812f8) | `` automatic update `` |
| [`13192c30`](https://github.com/nix-community/NUR/commit/13192c3029968b182b4654cccec42289944f609c) | `` automatic update `` |
| [`4680fc33`](https://github.com/nix-community/NUR/commit/4680fc334df27df13fe855d30a51990a1c9975c7) | `` automatic update `` |
| …
> chore(flake/nur): `60fcca8c` -> `20a5ac55`

- flake.lock
| [`7b068bb0`](https://github.com/nix-community/NUR/commit/7b068bb0f5c4554cf6686ba71900d746afe844e7) | `` automatic update `` |
| [`2e99d8ca`](https://github.com/nix-community/NUR/commit/2e99d8ca64f472e72e8b16579916bd97e7908665) | `` automatic update `` |
| [`a326a72a`](https://github.com/nix-community/NUR/commit/a326a72a439e923ffc9b049b5ac2974900701ff9) | `` automatic update `` |
| [`7e9f722d`](https://github.com/nix-community/NUR/commit/7e9f722dea58e890a63165bad793789f654dbc1e) | `` automatic update `` |
| …
> chore(flake/nur): `7d7cbe07` -> `7b068bb0`

- flake.lock
| [`f2892614`](https://github.com/nix-community/NUR/commit/f28926144028124438f44689ebad274e399e7767) | `` automatic update `` |
| [`fe37aa62`](https://github.com/nix-community/NUR/commit/fe37aa627ddb903c7843adc93cef55cb1f4e0047) | `` automatic update `` |
| [`bdf0b388`](https://github.com/nix-community/NUR/commit/bdf0b3886aed8a9f967c15d14ea9a878ea67b8af) | `` automatic update `` |
| [`2d829077`](https://github.com/nix-community/NUR/commit/2d829077a839f1a5015b91d622ff0721edd66d46) | `` automatic update `` |
| …
> chore(flake/nur): `7b068bb0` -> `f2892614`

- flake.lock
| [`2562a581`](https://github.com/Gerg-L/spicetify-nix/commit/2562a5819140581377530077888b37137d2d05fc) | `` CI update 2024-10-26 `` |
> chore(flake/spicetify-nix): `ebbc0161` -> `2562a581`

- flake.lock
| [`5b2a08e2`](https://github.com/nix-community/nix-vscode-extensions/commit/5b2a08e28a23bd1b0e749aca0240d35405c7b019) | `` action `` |
> chore(flake/nix-vscode-extensions): `0d53b783` -> `5b2a08e2`

- flake.lock
| [`b26d0afa`](https://github.com/nix-community/NUR/commit/b26d0afa34544d1fc46d53a80f4fc579244630fb) | `` automatic update `` |
| [`5e6fa8d9`](https://github.com/nix-community/NUR/commit/5e6fa8d9ef385f649e9166ac5ce2d170e7b194c1) | `` automatic update `` |
| [`8a6cabe5`](https://github.com/nix-community/NUR/commit/8a6cabe5ed2e5e1bd926c9fa0e0c6622fc735702) | `` automatic update `` |
| [`b5a18379`](https://github.com/nix-community/NUR/commit/b5a183792af4dda943103e04152d90d5d5c99d9e) | `` automatic update `` |
| …
> chore(flake/nur): `f2892614` -> `b26d0afa`

- flake.lock
| Commit                                                                                           | Message                                           |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------- |
| [`a3d3b4fd`](https://github.com/hyprwm/Hyprland/commit/a3d3b4fd64a51a8c1663b450bd2a408f1f0fa9b3) | `` groups: fix swallowing (#8223) ``              |
| [`f3f7d362`](https://github.com/hyprwm/Hyprland/commit/f3f7d3629a632682b1b3acf800f0b5fb10cd48f4) | `` Build with hyprland-session.service (#8251) `` |
| [`c356e425`](https://github.com/hyprwm/Hyprland/commit/c356e425008cba8bd0c87487a2c79b9be4eda2aa) | `` misc: Fix bad links to wiki (#8240) ``         |
> chore(flake/hyprland): `0b29caf9` -> `a3d3b4fd`

- flake.lock
| [`9418361f`](https://github.com/Gerg-L/spicetify-nix/commit/9418361fae1e426a8f8957a7bfc6ddc72882ce2c) | `` CI update 2024-10-27 `` |
> chore(flake/spicetify-nix): `2562a581` -> `9418361f`

- flake.lock
| [`88bf7381`](https://github.com/nix-community/nix-vscode-extensions/commit/88bf73817636e232513bff1f3a071b3ae2bcfd14) | `` action `` |
> chore(flake/nix-vscode-extensions): `5b2a08e2` -> `88bf7381`

- flake.lock
| [`a9de36f4`](https://github.com/nix-community/NUR/commit/a9de36f431ea62348111585cfba0f50acc58acac) | `` automatic update `` |
| [`c99f74da`](https://github.com/nix-community/NUR/commit/c99f74da05c901e064eb98218844ad652f7f9216) | `` automatic update `` |
| [`45c76459`](https://github.com/nix-community/NUR/commit/45c7645988b4d8749beae7cd25e4dee4d44078fc) | `` automatic update `` |
| [`b183dd49`](https://github.com/nix-community/NUR/commit/b183dd494dc3138db500a64cdda1c3c91ac7d607) | `` automatic update `` |
| …
> chore(flake/nur): `b26d0afa` -> `a9de36f4`

- flake.lock
| [`917fe0f3`](https://github.com/nix-community/NUR/commit/917fe0f398348a7a3aec3336b07a35d4cbc2d604) | `` automatic update `` |
| [`603aabf5`](https://github.com/nix-community/NUR/commit/603aabf5f43db015608c3473cb4236421fd47166) | `` automatic update `` |
| [`3c37170b`](https://github.com/nix-community/NUR/commit/3c37170bae2ccb25c48103442e1564e5e377cc22) | `` automatic update `` |
| [`957b94ad`](https://github.com/nix-community/NUR/commit/957b94ad2381e6bafdb21c092162549af42f185c) | `` automatic update `` |
| …
> chore(flake/nur): `a9de36f4` -> `917fe0f3`

- flake.lock
| [`1c482c8b`](https://github.com/Gerg-L/spicetify-nix/commit/1c482c8baffd494119b7f61735d35c62a0a22244) | `` CI update 2024-10-30 `` |
> chore(flake/spicetify-nix): `446351c3` -> `1c482c8b`

- flake.lock
| [`259d80a6`](https://github.com/nix-community/NUR/commit/259d80a6b86f67106c0559a83ac3406a8162a500) | `` automatic update `` |
| [`b5685d21`](https://github.com/nix-community/NUR/commit/b5685d217aa8054c68539e656eb3cc1d3962e4df) | `` automatic update `` |
| [`c9c4d887`](https://github.com/nix-community/NUR/commit/c9c4d88756f0fe72fb3100464f8759379292960f) | `` automatic update `` |
| [`664a098d`](https://github.com/nix-community/NUR/commit/664a098d8fd59ba06980b8ec39fee92d4c213096) | `` automatic update `` |
| …
> chore(flake/nur): `142092eb` -> `259d80a6`

- flake.lock
| [`761c6a7d`](https://github.com/nix-community/NUR/commit/761c6a7d6859126681d206126ba26ec58306d068) | `` automatic update `` |
| [`3f561643`](https://github.com/nix-community/NUR/commit/3f56164326915180b00cf69913c248036fa0048c) | `` automatic update `` |
| [`a85fbb5b`](https://github.com/nix-community/NUR/commit/a85fbb5b9b7ea836eb40cc4e0ff5f467bdba0cb0) | `` automatic update `` |
| [`e49c6352`](https://github.com/nix-community/NUR/commit/e49c6352513dc101f4c1048acbc923a4048d8225) | `` automatic update `` |
| …
> chore(flake/nur): `259d80a6` -> `761c6a7d`

- flake.lock
| [`191323d8`](https://github.com/Gerg-L/spicetify-nix/commit/191323d81e19efa0be5071e17263851e62f35685) | `` CI update 2024-11-02 `` |
> chore(flake/spicetify-nix): `defcdbfd` -> `191323d8`

- flake.lock
| [`a6d4683c`](https://github.com/nix-community/nix-vscode-extensions/commit/a6d4683cb3b0b3b846015196c8938cdeb5ffc2d9) | `` action `` |
> chore(flake/nix-vscode-extensions): `96dcbddd` -> `a6d4683c`

- flake.lock
| [`62fa5dcf`](https://github.com/nix-community/NUR/commit/62fa5dcf74c3d2cae2d207926572614489e78815) | `` automatic update `` |
| [`3199e01a`](https://github.com/nix-community/NUR/commit/3199e01a7dc67e11dd0c175f0c6559fb5328c707) | `` automatic update `` |
| [`198ff483`](https://github.com/nix-community/NUR/commit/198ff48341da4b09852742195d664d13872c7a37) | `` automatic update `` |
| [`561a4453`](https://github.com/nix-community/NUR/commit/561a44537cc94620665ad8dfa36266d2851c99c3) | `` automatic update `` |
| …
> chore(flake/nur): `187f8309` -> `62fa5dcf`

- flake.lock
| [`e8da0ed9`](https://github.com/nix-community/NUR/commit/e8da0ed9265ebaf94839d910a0c168b9941aa2ed) | `` automatic update `` |
| [`32892eee`](https://github.com/nix-community/NUR/commit/32892eee6299e1948ccc7708680f503359205432) | `` automatic update `` |
| [`f9845334`](https://github.com/nix-community/NUR/commit/f984533422fba1872b8b4191bbb489ce83981d18) | `` automatic update `` |
| [`805e768e`](https://github.com/nix-community/NUR/commit/805e768e781baae448a5f7300e49ed7fc99257c4) | `` automatic update `` |
| …
> chore(flake/nur): `62fa5dcf` -> `e8da0ed9`

- flake.lock
| [`4a91ab65`](https://github.com/nix-community/nix-vscode-extensions/commit/4a91ab65b7d145e15d1be7469f3bc2198f9c9185) | `` action `` |
> chore(flake/nix-vscode-extensions): `a6d4683c` -> `4a91ab65`

- flake.lock
| [`c29215e2`](https://github.com/Gerg-L/spicetify-nix/commit/c29215e233ddd504d670d432095fbba7e541b880) | `` CI update 2024-11-03 `` |
> chore(flake/spicetify-nix): `191323d8` -> `c29215e2`

- flake.lock
| [`2723e4e5`](https://github.com/nix-community/NUR/commit/2723e4e5073ac0ae4ec107cd75697df6b1165603) | `` automatic update `` |
| [`4ad55c01`](https://github.com/nix-community/NUR/commit/4ad55c01c89c310302475c287e2d9602fb9edfab) | `` automatic update `` |
| [`b73273c8`](https://github.com/nix-community/NUR/commit/b73273c89b6cd4f8d845ef0374647638c60496c3) | `` automatic update `` |
| [`27ef0fba`](https://github.com/nix-community/NUR/commit/27ef0fba0927d02c697a47d5f68658de1c9ac0b4) | `` automatic update `` |
| …
> chore(flake/nur): `e8da0ed9` -> `2723e4e5`

- flake.lock
| Commit                                                                                           | Message                                                                                                 |
| ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------- |
| [`31422ae2`](https://github.com/hyprwm/Hyprland/commit/31422ae25dee33dd000798b64a80bd7fd08d2ece) | `` windowrules: add negative: prefix for negating a regex ``                                            |
| [`57921d7d`](https://github.com/hyprwm/Hyprland/commit/57921d7dbd1b87a9474f609cb9cd30e6174027cd) | `` windowrules: precompute regexes for window/layer rules `` …
> chore(flake/hyprland): `db249648` -> `31422ae2`

- flake.lock
| Commit                                                                                           | Message                                                                            |
| ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------- |
| [`67e1e46f`](https://github.com/hyprwm/Hyprland/commit/67e1e46f9b6285ea260bc88844f85dec6b7d7d02) | `` window: fixup fade out animation on silent moves ``                             |
| [`308b1f3a`](https://github.com/hyprwm/Hyprland/commit/308b1f3afbb150fa008e3147faeee5d3ba7e6876) | `` core: minor fixes for animation rewrite ``                                      |
| …
> chore(flake/hyprland): `1989b004` -> `67e1e46f`
